$axure.loadCurrentPage({
  "url":"拼车.html",
  "generationDate":new Date(1419937539451.69),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b93dc50bae744227b8034a3cb994cb48",
    "type":"Axure:Page",
    "name":"拼车",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"29a2af79da344d71be94a08ad1cf8ee0",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"c0a6f8e65f9843a4bd1f1d0f4546bc5c"},
{
          "id":"08f933f6e5d744ada015277ebbcc4ae2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":85},
            "size":{
              "width":1192,
              "height":502}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"155d0ace2e70436ea72e29a58c0bc6b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":85},
                "size":{
                  "width":1192,
                  "height":502}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拼车/u5.png"}},
{
          "id":"e84eb9803b144490865cc34572e2bf51",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":153,
              "y":288},
            "size":{
              "width":1188,
              "height":126}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3ede8479a684d9282219557175bbfdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":153,
                  "y":288},
                "size":{
                  "width":1188,
                  "height":126}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拼车/u7.png"}},
{
          "id":"6a0f4edf5f9546c6b04c3ca68005bcf5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":290},
            "size":{
              "width":1170,
              "height":32},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0b3a90fd715497db69759d03cffe35c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":290},
                "size":{
                  "width":1170,
                  "height":32},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拼车/u9.png"}},
{
          "id":"25faaafa69e54bb6bdf7d33898821251",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":234,
              "y":298},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abee50c8fdd548dd97b73825a416e2dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":234,
                  "y":298},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"456084a3f5d7477ba14eb136c7bcd9da",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":298},
            "size":{
              "width":46,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"124e6bfe9a9145b2a73f1eb2adea5365",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":309,
                  "y":298},
                "size":{
                  "width":46,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onCheckedChange":{
              "description":"OnCheckedChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 takeupBus,<br>takeoffBus",
                      "objectsToFades":[{
                          "objectPath":["c32ff94fb09145a39c226be9d61f2654"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["853c430bdb204cdca11008fccb01ca8b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}}},
{
          "id":"63adbb1a7b1c4a61937f32d4ed4fa30b",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":355,
              "y":298},
            "size":{
              "width":46,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b5e0e29eac64ad7bec8800336b068fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":355,
                  "y":298},
                "size":{
                  "width":46,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onCheckedChange":{
              "description":"OnCheckedChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 takeupBoat,<br>takeoffBoat",
                      "objectsToFades":[{
                          "objectPath":["a557ec37ed144c4e8417effde0532394"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["59f0f5ada4d240b9bcfaa7fe33f3d409"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}}},
{
          "id":"cc95a25f480a4d5d8cc096c1fc058cd0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":583},
            "size":{
              "width":1188,
              "height":412}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de36c9f63fa1457b9096ac55c701cb31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":151,
                  "y":583},
                "size":{
                  "width":1188,
                  "height":412}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拼车/u17.png"}},
{
          "id":"c32ff94fb09145a39c226be9d61f2654",
          "label":"takeupBus",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":320,
              "y":690},
            "size":{
              "width":81,
              "height":20},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d21013e4c0af45be85931d48b0a3b45b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":320,
                  "y":690},
                "size":{
                  "width":81,
                  "height":20},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拼车/takeupbus_u19.png"}},
{
          "id":"853c430bdb204cdca11008fccb01ca8b",
          "label":"takeoffBus",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":320,
              "y":726},
            "size":{
              "width":81,
              "height":20},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57e7a5cfd87942ad8e1401c48bf27461",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":320,
                  "y":726},
                "size":{
                  "width":81,
                  "height":20},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拼车/takeupbus_u19.png"}},
{
          "id":"a557ec37ed144c4e8417effde0532394",
          "label":"takeupBoat",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":320,
              "y":690},
            "size":{
              "width":81,
              "height":20},
            "visible":false,
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"879f18f7951e44afb5d47d56164611de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":320,
                  "y":690},
                "size":{
                  "width":81,
                  "height":20},
                "visible":false,
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拼车/takeupbus_u19.png"}},
{
          "id":"59f0f5ada4d240b9bcfaa7fe33f3d409",
          "label":"takeoffBoat",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":320,
              "y":726},
            "size":{
              "width":81,
              "height":20},
            "visible":false,
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0feebe03836a44368b48bb1eecfc3a86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":320,
                  "y":726},
                "size":{
                  "width":81,
                  "height":20},
                "visible":false,
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拼车/takeupbus_u19.png"}},
{
          "id":"95380e63570244deadfc05a326f3b74c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":780},
            "size":{
              "width":680,
              "height":200},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5935a740f24d4fd9a9fcc67c5d260181",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":780},
                "size":{
                  "width":680,
                  "height":200},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拼车/u27.png"}},
{
          "id":"b1f37af00f624d818173d679377d998d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":790},
            "size":{
              "width":680,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2c8bee7d2c545dd8584a21958155fed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":790},
                "size":{
                  "width":680,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拼车/u29.png"}},
{
          "id":"7220e85fa12c494a987ddc497c11f101",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":914,
              "y":1039},
            "size":{
              "width":87,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94971af5e09a46e1ad35c532ccd425a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":914,
                  "y":1039},
                "size":{
                  "width":87,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拼车/u31.png"}},
{
          "id":"61f419f2716347fe85a15b166216f375",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":149,
              "y":1073},
            "size":{
              "width":1191,
              "height":469}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de1b37c333c94f9ba31cd67b6cf7331e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":149,
                  "y":1073},
                "size":{
                  "width":1191,
                  "height":469}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拼车/u33.png"}}]}},
  "masters":{
    "c0a6f8e65f9843a4bd1f1d0f4546bc5c":{
      "packageId":"c0a6f8e65f9843a4bd1f1d0f4546bc5c",
      "type":"Axure:Master",
      "name":"产品管理",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"5024326008c74a3f90f4004ca3eb09ad",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":1364,
                "height":667}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3533708ddaf64d53ab22ac58fbcf7457",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1364,
                    "height":667}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/酒店/u1.png"}},
{
            "id":"b3d7ad7f6d44402fbfdfac4c0f1e8cb0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":140,
                "y":76},
              "size":{
                "width":1226,
                "height":591},
              "linePattern":"none"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b3e89a31a0f041cbbc6ef6f867f6e9ca",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":140,
                    "y":76},
                  "size":{
                    "width":1226,
                    "height":591},
                  "linePattern":"none"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/酒店/u3.png"}}]}}},
  "objectPaths":{
    "29a2af79da344d71be94a08ad1cf8ee0":{
      "scriptId":"u0",
      "5024326008c74a3f90f4004ca3eb09ad":{
        "scriptId":"u1"},
      "3533708ddaf64d53ab22ac58fbcf7457":{
        "scriptId":"u2"},
      "b3d7ad7f6d44402fbfdfac4c0f1e8cb0":{
        "scriptId":"u3"},
      "b3e89a31a0f041cbbc6ef6f867f6e9ca":{
        "scriptId":"u4"}},
    "08f933f6e5d744ada015277ebbcc4ae2":{
      "scriptId":"u5"},
    "155d0ace2e70436ea72e29a58c0bc6b9":{
      "scriptId":"u6"},
    "e84eb9803b144490865cc34572e2bf51":{
      "scriptId":"u7"},
    "d3ede8479a684d9282219557175bbfdb":{
      "scriptId":"u8"},
    "6a0f4edf5f9546c6b04c3ca68005bcf5":{
      "scriptId":"u9"},
    "d0b3a90fd715497db69759d03cffe35c":{
      "scriptId":"u10"},
    "25faaafa69e54bb6bdf7d33898821251":{
      "scriptId":"u11"},
    "abee50c8fdd548dd97b73825a416e2dd":{
      "scriptId":"u12"},
    "456084a3f5d7477ba14eb136c7bcd9da":{
      "scriptId":"u13"},
    "124e6bfe9a9145b2a73f1eb2adea5365":{
      "scriptId":"u14"},
    "63adbb1a7b1c4a61937f32d4ed4fa30b":{
      "scriptId":"u15"},
    "3b5e0e29eac64ad7bec8800336b068fc":{
      "scriptId":"u16"},
    "cc95a25f480a4d5d8cc096c1fc058cd0":{
      "scriptId":"u17"},
    "de36c9f63fa1457b9096ac55c701cb31":{
      "scriptId":"u18"},
    "c32ff94fb09145a39c226be9d61f2654":{
      "scriptId":"u19"},
    "d21013e4c0af45be85931d48b0a3b45b":{
      "scriptId":"u20"},
    "853c430bdb204cdca11008fccb01ca8b":{
      "scriptId":"u21"},
    "57e7a5cfd87942ad8e1401c48bf27461":{
      "scriptId":"u22"},
    "a557ec37ed144c4e8417effde0532394":{
      "scriptId":"u23"},
    "879f18f7951e44afb5d47d56164611de":{
      "scriptId":"u24"},
    "59f0f5ada4d240b9bcfaa7fe33f3d409":{
      "scriptId":"u25"},
    "0feebe03836a44368b48bb1eecfc3a86":{
      "scriptId":"u26"},
    "95380e63570244deadfc05a326f3b74c":{
      "scriptId":"u27"},
    "5935a740f24d4fd9a9fcc67c5d260181":{
      "scriptId":"u28"},
    "b1f37af00f624d818173d679377d998d":{
      "scriptId":"u29"},
    "f2c8bee7d2c545dd8584a21958155fed":{
      "scriptId":"u30"},
    "7220e85fa12c494a987ddc497c11f101":{
      "scriptId":"u31"},
    "94971af5e09a46e1ad35c532ccd425a7":{
      "scriptId":"u32"},
    "61f419f2716347fe85a15b166216f375":{
      "scriptId":"u33"},
    "de1b37c333c94f9ba31cd67b6cf7331e":{
      "scriptId":"u34"}}});