$axure.loadCurrentPage({
  "url":"电话卡.html",
  "generationDate":new Date(1419937539816.71),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"20d202da48904d908c52df15e5710f4b",
    "type":"Axure:Page",
    "name":"电话卡",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4171b604e1e0422a86bbe47b9aff5e20",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"c0a6f8e65f9843a4bd1f1d0f4546bc5c"},
{
          "id":"40db898987b8487cb988ec6374c6a244",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":85},
            "size":{
              "width":1189,
              "height":205},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1682b25e65704c4c84eefe40c860054f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":85},
                "size":{
                  "width":1189,
                  "height":205},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/电话卡/u5.png"}},
{
          "id":"c69b27c54b6549f4a6b2b77d253877a6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":333},
            "size":{
              "width":1189,
              "height":175},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"510ccf970b4748ff9083f3d38643b78c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":333},
                "size":{
                  "width":1189,
                  "height":175},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/电话卡/u7.png"}},
{
          "id":"91e1390d0ca641d996263f5717f6e382",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":507},
            "size":{
              "width":1189,
              "height":135},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff3afc521163496795335f6d471f1199",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":507},
                "size":{
                  "width":1189,
                  "height":135},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/电话卡/u9.png"}},
{
          "id":"cc5a6e0d83ab44a8b2fe5ffd0cb7fd6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":309,
              "y":180},
            "size":{
              "width":70,
              "height":30},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d78a3302e9524eafb0ab35bca2241a60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":309,
                  "y":180},
                "size":{
                  "width":70,
                  "height":30},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/电话卡/u11.png"}},
{
          "id":"25843cd2e69547698a8db167777a56ee",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":152,
              "y":287},
            "size":{
              "width":1186,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b8ae568586a454f86809d2f78ede633",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":152,
                  "y":287},
                "size":{
                  "width":1186,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/票券/u15.png"}},
{
          "id":"2ab3d4c07bac46ff95056533db57dd00",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":233,
              "y":304},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e617404b8a24a69826a8d7b6403f219",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":233,
                  "y":304},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46cf9672308c43e9a2b73e278d276df4",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":309,
              "y":299},
            "size":{
              "width":91,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9a172bee4fed488394fb773f45fb8d89",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":299},
            "size":{
              "width":150,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a80679382eb341dda75e45f9f9962208",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":299},
                "size":{
                  "width":150,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a1bbecb26db4a22b28cdb3f1d07aca4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":406,
              "y":187},
            "size":{
              "width":454,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"238c5380076c4cc4b3c9d935b1c2958c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":406,
                  "y":187},
                "size":{
                  "width":454,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"789a5a6b5aed4a9d98be6e1e93b78756",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":637},
            "size":{
              "width":1190,
              "height":399},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ef2c3ba36e047d0b9c6ef13cb2aa37c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":637},
                "size":{
                  "width":1190,
                  "height":399},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/电话卡/u22.png"}},
{
          "id":"07e202a4729d48f09d380310c05b703a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":1036},
            "size":{
              "width":1188,
              "height":423},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c298dc9aec314e44a116fa06a378f05e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":1036},
                "size":{
                  "width":1188,
                  "height":423},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/票券/u22.png"}},
{
          "id":"19a4aaea6eb24732b263915d559c69d2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":1454},
            "size":{
              "width":1189,
              "height":159}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a8ab3034c854ef7acad4cab6d8296c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":1454},
                "size":{
                  "width":1189,
                  "height":159}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/票券/u24.png"}}]}},
  "masters":{
    "c0a6f8e65f9843a4bd1f1d0f4546bc5c":{
      "packageId":"c0a6f8e65f9843a4bd1f1d0f4546bc5c",
      "type":"Axure:Master",
      "name":"产品管理",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"5024326008c74a3f90f4004ca3eb09ad",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":1364,
                "height":667}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3533708ddaf64d53ab22ac58fbcf7457",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1364,
                    "height":667}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/酒店/u1.png"}},
{
            "id":"b3d7ad7f6d44402fbfdfac4c0f1e8cb0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":140,
                "y":76},
              "size":{
                "width":1226,
                "height":591},
              "linePattern":"none"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b3e89a31a0f041cbbc6ef6f867f6e9ca",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":140,
                    "y":76},
                  "size":{
                    "width":1226,
                    "height":591},
                  "linePattern":"none"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/酒店/u3.png"}}]}}},
  "objectPaths":{
    "4171b604e1e0422a86bbe47b9aff5e20":{
      "scriptId":"u0",
      "5024326008c74a3f90f4004ca3eb09ad":{
        "scriptId":"u1"},
      "3533708ddaf64d53ab22ac58fbcf7457":{
        "scriptId":"u2"},
      "b3d7ad7f6d44402fbfdfac4c0f1e8cb0":{
        "scriptId":"u3"},
      "b3e89a31a0f041cbbc6ef6f867f6e9ca":{
        "scriptId":"u4"}},
    "40db898987b8487cb988ec6374c6a244":{
      "scriptId":"u5"},
    "1682b25e65704c4c84eefe40c860054f":{
      "scriptId":"u6"},
    "c69b27c54b6549f4a6b2b77d253877a6":{
      "scriptId":"u7"},
    "510ccf970b4748ff9083f3d38643b78c":{
      "scriptId":"u8"},
    "91e1390d0ca641d996263f5717f6e382":{
      "scriptId":"u9"},
    "ff3afc521163496795335f6d471f1199":{
      "scriptId":"u10"},
    "cc5a6e0d83ab44a8b2fe5ffd0cb7fd6c":{
      "scriptId":"u11"},
    "d78a3302e9524eafb0ab35bca2241a60":{
      "scriptId":"u12"},
    "25843cd2e69547698a8db167777a56ee":{
      "scriptId":"u13"},
    "3b8ae568586a454f86809d2f78ede633":{
      "scriptId":"u14"},
    "2ab3d4c07bac46ff95056533db57dd00":{
      "scriptId":"u15"},
    "2e617404b8a24a69826a8d7b6403f219":{
      "scriptId":"u16"},
    "46cf9672308c43e9a2b73e278d276df4":{
      "scriptId":"u17"},
    "9a172bee4fed488394fb773f45fb8d89":{
      "scriptId":"u18"},
    "a80679382eb341dda75e45f9f9962208":{
      "scriptId":"u19"},
    "4a1bbecb26db4a22b28cdb3f1d07aca4":{
      "scriptId":"u20"},
    "238c5380076c4cc4b3c9d935b1c2958c":{
      "scriptId":"u21"},
    "789a5a6b5aed4a9d98be6e1e93b78756":{
      "scriptId":"u22"},
    "1ef2c3ba36e047d0b9c6ef13cb2aa37c":{
      "scriptId":"u23"},
    "07e202a4729d48f09d380310c05b703a":{
      "scriptId":"u24"},
    "c298dc9aec314e44a116fa06a378f05e":{
      "scriptId":"u25"},
    "19a4aaea6eb24732b263915d559c69d2":{
      "scriptId":"u26"},
    "2a8ab3034c854ef7acad4cab6d8296c2":{
      "scriptId":"u27"}}});