$axure.loadCurrentPage({
  "url":"当地游.html",
  "generationDate":new Date(1419937539731.71),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"313d2c98f3324acdaf10d81933270690",
    "type":"Axure:Page",
    "name":"当地游",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a3bf073ffa3840c3b81674c62fc722c4",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"c0a6f8e65f9843a4bd1f1d0f4546bc5c"},
{
          "id":"d7815174fcf94fa7bd0c1c6294602e95",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":85},
            "size":{
              "width":1193,
              "height":554}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d65db883f61a40e7acdc1f2eafe322cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":85},
                "size":{
                  "width":1193,
                  "height":554}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/当地游/u5.png"}},
{
          "id":"b8127297fba64401a9ed08c972658f24",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":683,
              "y":219},
            "size":{
              "width":37,
              "height":28},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7a011f7000540548f374a72549db838",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":683,
                  "y":219},
                "size":{
                  "width":37,
                  "height":28},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/当地游/u7.png"}},
{
          "id":"bfcf947b942e4079a63c5ebb210a7231",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":706,
              "y":217},
            "size":{
              "width":366,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2b72307851348d48dc9ccac3687c931",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":706,
                  "y":217},
                "size":{
                  "width":366,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/当地游/u9.png"}},
{
          "id":"fcad0236065f41919f2c3ffef13c0cd4",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":221},
            "size":{
              "width":45,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"37c4f29a19c04b6fa465477a49ae3993",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":666,
              "y":173},
            "size":{
              "width":425,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20ed5b1fb6844bb19f647def0afa0520",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":666,
                  "y":173},
                "size":{
                  "width":425,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"517f32b7ee1742cb85739d835bc87f46",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":152,
              "y":635},
            "size":{
              "width":1188,
              "height":47}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b32a26acbb64d228e1bb48f094266e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":152,
                  "y":635},
                "size":{
                  "width":1188,
                  "height":47}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/当地游/u14.png"}},
{
          "id":"b207b5f403af4164905e882930dce359",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":149,
              "y":677},
            "size":{
              "width":1192,
              "height":265}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cb9a7939461430a84db54edc0b6bc00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":149,
                  "y":677},
                "size":{
                  "width":1192,
                  "height":265}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/当地游/u16.png"}},
{
          "id":"04c3560f92514ba1bcbdfcc43a758767",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":317,
              "y":780},
            "size":{
              "width":680,
              "height":200},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed94a05352c34245abce2a4042a49bc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":317,
                  "y":780},
                "size":{
                  "width":680,
                  "height":200},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拼车/u27.png"}},
{
          "id":"a75cdd45158d4906a9f0c4c42935ef5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":322,
              "y":785},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09aa09a2b7bf46708ee66156e916012f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":322,
                  "y":785},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ea1f8d32d484b009a220894345eb0e7",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":388,
              "y":785},
            "size":{
              "width":112,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4907bff063d74e18a3c7ac7cfd6a0891",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":388,
                  "y":785},
                "size":{
                  "width":112,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"e07a4c915195461cb50bad2cde2e555a",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":518,
              "y":785},
            "size":{
              "width":112,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a94e4796d3347cd9bf05790a3f96895",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":518,
                  "y":785},
                "size":{
                  "width":112,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"f679c4d5a15d4214bfe5e0ce68cf3522",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":387,
              "y":813},
            "size":{
              "width":410,
              "height":87}},
          "adaptiveStyles":{
}},
{
          "id":"5c742cc1e44f45599fa0b18c88d9d8ca",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":387,
              "y":910},
            "size":{
              "width":613,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"286751e1c07b4cf78d103a8f3138421e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":387,
                  "y":910},
                "size":{
                  "width":613,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拼车/u29.png"}},
{
          "id":"c1dd36c751ba4ef48c83da0404ce1b98",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":1124},
            "size":{
              "width":38,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df4d86b185734e31bc6484a4c8919ade",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":1124},
                "size":{
                  "width":38,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6126983e0db469ca392824ab0f89a67",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":388,
              "y":1119.5},
            "size":{
              "width":159,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"be704a51720c44ddbbfdb56ca3bd6211",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":587,
              "y":1124},
            "size":{
              "width":38,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"398f7ccf99444e99919b24e8d03361ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":587,
                  "y":1124},
                "size":{
                  "width":38,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3aad436c67fb457cab8cb12263129733",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":635,
              "y":1120},
            "size":{
              "width":159,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"54b385f80cb1435cac7407d9ca6d0e46",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":322,
              "y":910},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c08ff779c1b642abb0066bdb89053c13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":322,
                  "y":910},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8201910a8eb84f68ab7c8fb10e167a6f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":317,
              "y":1157},
            "size":{
              "width":675,
              "height":196}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fb5106d8fb94603afc33c66e253de82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":317,
                  "y":1157},
                "size":{
                  "width":675,
                  "height":196}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/当地游/u37.png"}},
{
          "id":"417dfbf821af4790ab63b6866d84150d",
          "label":"imgJQ",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":388,
              "y":1188},
            "size":{
              "width":213,
              "height":133},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"843de379fb924027b5af94cadc4c792d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":388,
                  "y":1188},
                "size":{
                  "width":213,
                  "height":133},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/当地游/imgjq_u39.png"}},
{
          "id":"eca3cb07a15c4329b64220d7528477e3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":388,
              "y":1163},
            "size":{
              "width":213,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 imgJQ",
                      "objectsToFades":[{
                          "objectPath":["417dfbf821af4790ab63b6866d84150d"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"87adad16fa32419cb5bab3bb5fa3d311",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":149,
              "y":1355},
            "size":{
              "width":1189,
              "height":475}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"321d82e815a84adb9fec9f40355677ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":149,
                  "y":1355},
                "size":{
                  "width":1189,
                  "height":475}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/当地游/u42.png"}}]}},
  "masters":{
    "c0a6f8e65f9843a4bd1f1d0f4546bc5c":{
      "packageId":"c0a6f8e65f9843a4bd1f1d0f4546bc5c",
      "type":"Axure:Master",
      "name":"产品管理",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"5024326008c74a3f90f4004ca3eb09ad",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":1364,
                "height":667}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3533708ddaf64d53ab22ac58fbcf7457",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1364,
                    "height":667}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/酒店/u1.png"}},
{
            "id":"b3d7ad7f6d44402fbfdfac4c0f1e8cb0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":140,
                "y":76},
              "size":{
                "width":1226,
                "height":591},
              "linePattern":"none"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b3e89a31a0f041cbbc6ef6f867f6e9ca",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":140,
                    "y":76},
                  "size":{
                    "width":1226,
                    "height":591},
                  "linePattern":"none"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/酒店/u3.png"}}]}}},
  "objectPaths":{
    "a3bf073ffa3840c3b81674c62fc722c4":{
      "scriptId":"u0",
      "5024326008c74a3f90f4004ca3eb09ad":{
        "scriptId":"u1"},
      "3533708ddaf64d53ab22ac58fbcf7457":{
        "scriptId":"u2"},
      "b3d7ad7f6d44402fbfdfac4c0f1e8cb0":{
        "scriptId":"u3"},
      "b3e89a31a0f041cbbc6ef6f867f6e9ca":{
        "scriptId":"u4"}},
    "d7815174fcf94fa7bd0c1c6294602e95":{
      "scriptId":"u5"},
    "d65db883f61a40e7acdc1f2eafe322cb":{
      "scriptId":"u6"},
    "b8127297fba64401a9ed08c972658f24":{
      "scriptId":"u7"},
    "a7a011f7000540548f374a72549db838":{
      "scriptId":"u8"},
    "bfcf947b942e4079a63c5ebb210a7231":{
      "scriptId":"u9"},
    "b2b72307851348d48dc9ccac3687c931":{
      "scriptId":"u10"},
    "fcad0236065f41919f2c3ffef13c0cd4":{
      "scriptId":"u11"},
    "37c4f29a19c04b6fa465477a49ae3993":{
      "scriptId":"u12"},
    "20ed5b1fb6844bb19f647def0afa0520":{
      "scriptId":"u13"},
    "517f32b7ee1742cb85739d835bc87f46":{
      "scriptId":"u14"},
    "8b32a26acbb64d228e1bb48f094266e0":{
      "scriptId":"u15"},
    "b207b5f403af4164905e882930dce359":{
      "scriptId":"u16"},
    "4cb9a7939461430a84db54edc0b6bc00":{
      "scriptId":"u17"},
    "04c3560f92514ba1bcbdfcc43a758767":{
      "scriptId":"u18"},
    "ed94a05352c34245abce2a4042a49bc3":{
      "scriptId":"u19"},
    "a75cdd45158d4906a9f0c4c42935ef5a":{
      "scriptId":"u20"},
    "09aa09a2b7bf46708ee66156e916012f":{
      "scriptId":"u21"},
    "9ea1f8d32d484b009a220894345eb0e7":{
      "scriptId":"u22"},
    "4907bff063d74e18a3c7ac7cfd6a0891":{
      "scriptId":"u23"},
    "e07a4c915195461cb50bad2cde2e555a":{
      "scriptId":"u24"},
    "3a94e4796d3347cd9bf05790a3f96895":{
      "scriptId":"u25"},
    "f679c4d5a15d4214bfe5e0ce68cf3522":{
      "scriptId":"u26"},
    "5c742cc1e44f45599fa0b18c88d9d8ca":{
      "scriptId":"u27"},
    "286751e1c07b4cf78d103a8f3138421e":{
      "scriptId":"u28"},
    "c1dd36c751ba4ef48c83da0404ce1b98":{
      "scriptId":"u29"},
    "df4d86b185734e31bc6484a4c8919ade":{
      "scriptId":"u30"},
    "c6126983e0db469ca392824ab0f89a67":{
      "scriptId":"u31"},
    "be704a51720c44ddbbfdb56ca3bd6211":{
      "scriptId":"u32"},
    "398f7ccf99444e99919b24e8d03361ca":{
      "scriptId":"u33"},
    "3aad436c67fb457cab8cb12263129733":{
      "scriptId":"u34"},
    "54b385f80cb1435cac7407d9ca6d0e46":{
      "scriptId":"u35"},
    "c08ff779c1b642abb0066bdb89053c13":{
      "scriptId":"u36"},
    "8201910a8eb84f68ab7c8fb10e167a6f":{
      "scriptId":"u37"},
    "7fb5106d8fb94603afc33c66e253de82":{
      "scriptId":"u38"},
    "417dfbf821af4790ab63b6866d84150d":{
      "scriptId":"u39"},
    "843de379fb924027b5af94cadc4c792d":{
      "scriptId":"u40"},
    "eca3cb07a15c4329b64220d7528477e3":{
      "scriptId":"u41"},
    "87adad16fa32419cb5bab3bb5fa3d311":{
      "scriptId":"u42"},
    "321d82e815a84adb9fec9f40355677ab":{
      "scriptId":"u43"}}});