$axure.loadCurrentPage({
  "url":"首页.html",
  "generationDate":new Date(1419937538959.66),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ebbe854c7229416e8e7598c06923d1c9",
    "type":"Axure:Page",
    "name":"首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2fd3b9e67cdc4e9a9a63e9d18c949375",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1364,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16a76310c613488d918518bd2d895986",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1364,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"6eb430ba1cdd4013960473390bdafc9b",
          "label":"imgProduct",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":235,
              "y":16},
            "size":{
              "width":90,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea9f66b868a54b50bcfc66390304bd64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":235,
                  "y":16},
                "size":{
                  "width":90,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 产品列表",
                      "target":{
                        "targetType":"page",
                        "url":"产品列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/imgproduct_u2.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "2fd3b9e67cdc4e9a9a63e9d18c949375":{
      "scriptId":"u0"},
    "16a76310c613488d918518bd2d895986":{
      "scriptId":"u1"},
    "6eb430ba1cdd4013960473390bdafc9b":{
      "scriptId":"u2"},
    "ea9f66b868a54b50bcfc66390304bd64":{
      "scriptId":"u3"}}});