$axure.loadCurrentPage({
  "url":"票券.html",
  "generationDate":new Date(1419937539630.7),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e6327aa7d68b4612a5a849b26c78065a",
    "type":"Axure:Page",
    "name":"票券",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e4039bc090914507a18225dd36f09c24",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"c0a6f8e65f9843a4bd1f1d0f4546bc5c"},
{
          "id":"de7529d482eb4091846e574646c2ebb0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":124},
            "size":{
              "width":1,
              "height":170},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b945c2890b64fbdbe4db672871afda5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":124},
                "size":{
                  "width":1,
                  "height":170},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/票券/u5.png"}},
{
          "id":"2973013c0417400f811d6825203101a3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":294},
            "size":{
              "width":1,
              "height":383},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19d7791fca84420b9432dd931ec08e37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":294},
                "size":{
                  "width":1,
                  "height":383},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/票券/u7.png"}},
{
          "id":"1a89e156f0c747a0bcc895f03a5352f4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":85},
            "size":{
              "width":1188,
              "height":170},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1f35defa41a484cafcc95be98e6862a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":151,
                  "y":85},
                "size":{
                  "width":1188,
                  "height":170},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/票券/u9.png"}},
{
          "id":"6cd8c44efc8846cd8f18c8fd02378465",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":304},
            "size":{
              "width":1188,
              "height":383},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"845d0be020bd4edda86bfca550633767",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":151,
                  "y":304},
                "size":{
                  "width":1188,
                  "height":383},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/票券/u11.png"}},
{
          "id":"ecd8fc801f744bd4a0647e50d253f8c5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":684},
            "size":{
              "width":1190,
              "height":444}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec0edab9e68f4716955e19d248094f9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":684},
                "size":{
                  "width":1190,
                  "height":444}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/票券/u13.png"}},
{
          "id":"7ff43478313e442eb2577fbfe4eae5ab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":152,
              "y":1123},
            "size":{
              "width":1186,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a145e46d7e3493f810be0cba819e37a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":152,
                  "y":1123},
                "size":{
                  "width":1186,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/票券/u15.png"}},
{
          "id":"6e28863db77c45df99d5ae5ea02ea8cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":237,
              "y":1143},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e346d7127c9c4d76ae7cf38b17e0a6e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":237,
                  "y":1143},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e9cbc393d7943eeb5ad5835a7261e50",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":1137},
            "size":{
              "width":385,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ee34d0a69db942ca92fd9315e2159246",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":1171},
            "size":{
              "width":1188,
              "height":81},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad2dba17dbfa4460b3811e9828744020",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":1171},
                "size":{
                  "width":1188,
                  "height":81},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/票券/u20.png"}},
{
          "id":"e1275256ff4d4e76a1742c4b7a11d45c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":1252},
            "size":{
              "width":1188,
              "height":423},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa19f0ed1079457c8b450086e2c59fda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":1252},
                "size":{
                  "width":1188,
                  "height":423},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/票券/u22.png"}},
{
          "id":"55946837ed164dd99123e64291eaa088",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":1669},
            "size":{
              "width":1189,
              "height":159}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"697128e6c8964b369c570442f4081c7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":1669},
                "size":{
                  "width":1189,
                  "height":159}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/票券/u24.png"}},
{
          "id":"bbb6c19cd51b4cc680da416c606fa1a7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":152,
              "y":252},
            "size":{
              "width":1186,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"beed29640fc14d87af03b6ef308e89f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":152,
                  "y":252},
                "size":{
                  "width":1186,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/票券/u15.png"}},
{
          "id":"f43304e7c3d74a3e8bcb48f093b7f37d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":270},
            "size":{
              "width":107,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbf855f55e9a44cb812256d53f886119",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":270},
                "size":{
                  "width":107,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1bd518830e27436b953651b7c568ad9d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":268},
            "size":{
              "width":410,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
    "c0a6f8e65f9843a4bd1f1d0f4546bc5c":{
      "packageId":"c0a6f8e65f9843a4bd1f1d0f4546bc5c",
      "type":"Axure:Master",
      "name":"产品管理",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"5024326008c74a3f90f4004ca3eb09ad",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":1364,
                "height":667}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3533708ddaf64d53ab22ac58fbcf7457",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1364,
                    "height":667}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/酒店/u1.png"}},
{
            "id":"b3d7ad7f6d44402fbfdfac4c0f1e8cb0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":140,
                "y":76},
              "size":{
                "width":1226,
                "height":591},
              "linePattern":"none"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b3e89a31a0f041cbbc6ef6f867f6e9ca",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":140,
                    "y":76},
                  "size":{
                    "width":1226,
                    "height":591},
                  "linePattern":"none"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/酒店/u3.png"}}]}}},
  "objectPaths":{
    "e4039bc090914507a18225dd36f09c24":{
      "scriptId":"u0",
      "5024326008c74a3f90f4004ca3eb09ad":{
        "scriptId":"u1"},
      "3533708ddaf64d53ab22ac58fbcf7457":{
        "scriptId":"u2"},
      "b3d7ad7f6d44402fbfdfac4c0f1e8cb0":{
        "scriptId":"u3"},
      "b3e89a31a0f041cbbc6ef6f867f6e9ca":{
        "scriptId":"u4"}},
    "de7529d482eb4091846e574646c2ebb0":{
      "scriptId":"u5"},
    "3b945c2890b64fbdbe4db672871afda5":{
      "scriptId":"u6"},
    "2973013c0417400f811d6825203101a3":{
      "scriptId":"u7"},
    "19d7791fca84420b9432dd931ec08e37":{
      "scriptId":"u8"},
    "1a89e156f0c747a0bcc895f03a5352f4":{
      "scriptId":"u9"},
    "e1f35defa41a484cafcc95be98e6862a":{
      "scriptId":"u10"},
    "6cd8c44efc8846cd8f18c8fd02378465":{
      "scriptId":"u11"},
    "845d0be020bd4edda86bfca550633767":{
      "scriptId":"u12"},
    "ecd8fc801f744bd4a0647e50d253f8c5":{
      "scriptId":"u13"},
    "ec0edab9e68f4716955e19d248094f9b":{
      "scriptId":"u14"},
    "7ff43478313e442eb2577fbfe4eae5ab":{
      "scriptId":"u15"},
    "6a145e46d7e3493f810be0cba819e37a":{
      "scriptId":"u16"},
    "6e28863db77c45df99d5ae5ea02ea8cb":{
      "scriptId":"u17"},
    "e346d7127c9c4d76ae7cf38b17e0a6e7":{
      "scriptId":"u18"},
    "8e9cbc393d7943eeb5ad5835a7261e50":{
      "scriptId":"u19"},
    "ee34d0a69db942ca92fd9315e2159246":{
      "scriptId":"u20"},
    "ad2dba17dbfa4460b3811e9828744020":{
      "scriptId":"u21"},
    "e1275256ff4d4e76a1742c4b7a11d45c":{
      "scriptId":"u22"},
    "aa19f0ed1079457c8b450086e2c59fda":{
      "scriptId":"u23"},
    "55946837ed164dd99123e64291eaa088":{
      "scriptId":"u24"},
    "697128e6c8964b369c570442f4081c7c":{
      "scriptId":"u25"},
    "bbb6c19cd51b4cc680da416c606fa1a7":{
      "scriptId":"u26"},
    "beed29640fc14d87af03b6ef308e89f8":{
      "scriptId":"u27"},
    "f43304e7c3d74a3e8bcb48f093b7f37d":{
      "scriptId":"u28"},
    "fbf855f55e9a44cb812256d53f886119":{
      "scriptId":"u29"},
    "1bd518830e27436b953651b7c568ad9d":{
      "scriptId":"u30"}}});