$axure.loadCurrentPage({
  "url":"附加费管理.html",
  "generationDate":new Date(1419937539329.69),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d41548f88d644f86af24cc8e1beb98e9",
    "type":"Axure:Page",
    "name":"附加费管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6a121406d0e442e188b2e3c5655fb191",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"c0a6f8e65f9843a4bd1f1d0f4546bc5c"},
{
          "id":"778aaf1f7123445794e9106376b51bf8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":85},
            "size":{
              "width":1211,
              "height":578}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"500effe609004ea0bfadd4a634e0f8cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":85},
                "size":{
                  "width":1211,
                  "height":578}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附加费管理/u5.png"}},
{
          "id":"117ce2a3e1174b80abc8e2ab5faa703d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":154,
              "y":254},
            "size":{
              "width":1206,
              "height":456}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6a27e81631548158faf0cb90c9e2f99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":154,
                  "y":254},
                "size":{
                  "width":1206,
                  "height":456}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附加费管理/u7.png"}},
{
          "id":"19a71df2ceff4c0c92176c92c5c62812",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":169,
              "y":209},
            "size":{
              "width":1181,
              "height":45},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1da0ca8dd093478585d74318e07e846a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":169,
                  "y":209},
                "size":{
                  "width":1181,
                  "height":45},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附加费管理/u9.png"}},
{
          "id":"a6b166ba74c64768a045161fd851c55a",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":221},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bf07723a46442e6a44c4ee81c8c2b61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":314,
                  "y":221},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"34ada7aff25d49eb8528710a9e041a25",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":254,
              "y":310},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac93b9a8842b4078b8be85f7619d8b4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":254,
                  "y":310},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"558aedee4dac4ab6bd89232b53ea28a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":334,
              "y":310},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f8b242998444767ab600412d6cc4cc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":334,
                  "y":310},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65bad7372f23473d8645168a21033e4f",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":642,
              "y":549},
            "size":{
              "width":130,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
    "c0a6f8e65f9843a4bd1f1d0f4546bc5c":{
      "packageId":"c0a6f8e65f9843a4bd1f1d0f4546bc5c",
      "type":"Axure:Master",
      "name":"产品管理",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"5024326008c74a3f90f4004ca3eb09ad",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":1364,
                "height":667}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3533708ddaf64d53ab22ac58fbcf7457",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1364,
                    "height":667}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/酒店/u1.png"}},
{
            "id":"b3d7ad7f6d44402fbfdfac4c0f1e8cb0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":140,
                "y":76},
              "size":{
                "width":1226,
                "height":591},
              "linePattern":"none"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b3e89a31a0f041cbbc6ef6f867f6e9ca",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":140,
                    "y":76},
                  "size":{
                    "width":1226,
                    "height":591},
                  "linePattern":"none"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/酒店/u3.png"}}]}}},
  "objectPaths":{
    "6a121406d0e442e188b2e3c5655fb191":{
      "scriptId":"u0",
      "5024326008c74a3f90f4004ca3eb09ad":{
        "scriptId":"u1"},
      "3533708ddaf64d53ab22ac58fbcf7457":{
        "scriptId":"u2"},
      "b3d7ad7f6d44402fbfdfac4c0f1e8cb0":{
        "scriptId":"u3"},
      "b3e89a31a0f041cbbc6ef6f867f6e9ca":{
        "scriptId":"u4"}},
    "778aaf1f7123445794e9106376b51bf8":{
      "scriptId":"u5"},
    "500effe609004ea0bfadd4a634e0f8cc":{
      "scriptId":"u6"},
    "117ce2a3e1174b80abc8e2ab5faa703d":{
      "scriptId":"u7"},
    "d6a27e81631548158faf0cb90c9e2f99":{
      "scriptId":"u8"},
    "19a71df2ceff4c0c92176c92c5c62812":{
      "scriptId":"u9"},
    "1da0ca8dd093478585d74318e07e846a":{
      "scriptId":"u10"},
    "a6b166ba74c64768a045161fd851c55a":{
      "scriptId":"u11"},
    "8bf07723a46442e6a44c4ee81c8c2b61":{
      "scriptId":"u12"},
    "34ada7aff25d49eb8528710a9e041a25":{
      "scriptId":"u13"},
    "ac93b9a8842b4078b8be85f7619d8b4f":{
      "scriptId":"u14"},
    "558aedee4dac4ab6bd89232b53ea28a2":{
      "scriptId":"u15"},
    "2f8b242998444767ab600412d6cc4cc8":{
      "scriptId":"u16"},
    "65bad7372f23473d8645168a21033e4f":{
      "scriptId":"u17"}}});