$axure.loadCurrentPage({
  "url":"酒店地面价格设置.html",
  "generationDate":new Date(1419937540436.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"42e85778b8b84100a3037b3b65be351d",
    "type":"Axure:Page",
    "name":"酒店地面价格设置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c4b2ade6f2324efb91ff708b10ce0066",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"c0a6f8e65f9843a4bd1f1d0f4546bc5c"},
{
          "id":"fb216cbb84f046a6b0026e2db2e6b03f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":85},
            "size":{
              "width":1209,
              "height":175}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be051d042d834166bfe5a3ba62ce26e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":85},
                "size":{
                  "width":1209,
                  "height":175}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店地面价格设置/u5.png"}},
{
          "id":"44e4aa2661c94b96940fd7b63dd0be33",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":200,
              "y":268},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecf930680d8c4c0690e0abe24f29a0b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":200,
                  "y":268},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e84798ae147a4785a222f5d8e7a61a6d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":266},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"65be1afbe8c248c4a217f65d469e6439",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":200,
              "y":303},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f4f20abfaec44b299cd8dd9d154e124",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":200,
                  "y":303},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2f8c4a434f3433ba6ebfddde380118a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":301},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"dd984f08b4044412b7ebbe2f9d273a8e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":466,
              "y":371},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7689b522b60b48dd8606bb41d821ddba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":203,
              "y":226},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c33778c7b1e4e44a18ea4154ac23790",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":203,
                  "y":226},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"51fc89f017ce4efd97d285dd98019a08",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":313,
              "y":218},
            "size":{
              "width":252,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ff8692b0bbb4bbfacf7d17f685f29bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":313,
                  "y":218},
                "size":{
                  "width":252,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店地面价格设置/u16.png"}},
{
          "id":"67a8a9923ffd4585b228f7ef405346e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":200,
              "y":335},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49132108e61341d08665c68da65bf193",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":200,
                  "y":335},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d7dcb11956d4ab08566ace7463a6703",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":335},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"cf9fdb25032542098a43f420c43ce688",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":370},
            "size":{
              "width":130,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8266bd983b3c4e0c8d121760319c7f80",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":200,
              "y":370},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41cb9e2b5a9c4c649b11351103bafd6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":200,
                  "y":370},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1627c71f299343f0b1c689097cfc623d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":603,
              "y":346},
            "size":{
              "width":647,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"272483bfb60c4a918ba33d40336960af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":603,
                  "y":346},
                "size":{
                  "width":647,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b970aa9d0aa4dd0a3a0a3618ecf7ecd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":204,
              "y":435},
            "size":{
              "width":1130,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/酒店地面价格设置/u26_line.png"}},
{
          "id":"daa42c111f5544f9b0681139b0c3abde",
          "label":"酒店套餐ID",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":200,
              "y":457},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5c19d1e5cfd4839925500724db98a4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":200,
                  "y":457},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d6626ce535840abb881be0d790bb0bd",
          "label":"txt酒店套餐ID",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":455},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6566508598424bc4b064727cd108ea8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":204,
              "y":422},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19fb21dcc1204802baf75f4c1741dd49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":204,
                  "y":422},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6800653212174311ac0af6aafe135830",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":200,
              "y":492},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f97a1c72d9fa43b39fe2bcefe1f69eb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":200,
                  "y":492},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e6e214f6133049dbb524460fff80872a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":490},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"71296753004b4981ac60d282c6e38c51",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":200,
              "y":569},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7c3e068147b46b3a3008a476a327b44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":200,
                  "y":569},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08c28e1ec67e42818240839b94838bb1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":567},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"909a0bbf72e0444189c8a1c1f7705e0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":200,
              "y":604},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18ddbbd327d84fcfbb221e2b54d21efb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":200,
                  "y":604},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38f218813a3e4364b6186011817a7457",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":602},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"41a3f5677ef846adb2f1576c2b43020d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":200,
              "y":639},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b48445ca0d446e5aaca9c14ec868913",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":200,
                  "y":639},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37ceb600ad7c4bef98150fbc62f6623b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":637},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"32e16c4bb2fb48868775f4ae096ee9ce",
          "label":"酒店套餐份数",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":457,
              "y":459},
            "size":{
              "width":57,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"495b773dfdad4a7ca13b75c531c697b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":457,
                  "y":459},
                "size":{
                  "width":57,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e1dc3b8fcbe54e2a938042f7d80fb5f5",
          "label":"txt酒店套餐份数",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":514,
              "y":456},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6980c726e96e474ab985d82cdd13061e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":567,
              "y":480},
            "size":{
              "width":40,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d53d3bcca0e48e0b09078d5d7235bee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":567,
                  "y":480},
                "size":{
                  "width":40,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 交通套餐+,<br>交通套餐ID,<br>txt交通套餐ID,<br>交通套餐份数,<br>txt交通套餐份数",
                      "objectsToFades":[{
                          "objectPath":["514af2fdb62d45b0ada8f65a11f4864d"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ef066ed8018a4b03af1ef9c26bb08066"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["65af2a1f4868418e9692868baead6bae"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["b9575fefe7294284b8d6eaa0555ee0c3"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["89a2cb5ca15e43e6a76fac1769d51874"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/酒店地面价格设置/u47.png"}},
{
          "id":"90932bc715a647e9a127f539a8366951",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":457,
              "y":488},
            "size":{
              "width":57,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0631c197643a43cd812ee2ee66d27b93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":457,
                  "y":488},
                "size":{
                  "width":57,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee61d2dc493d433d89afd8af84dc0f4a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":515,
              "y":486},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d5d8ad6628ea4da1adc4a950e00c7eb7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":567,
              "y":560},
            "size":{
              "width":40,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91b207a0ce374dc1b2b39ed335223739",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":567,
                  "y":560},
                "size":{
                  "width":40,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/酒店地面价格设置/u47.png"}},
{
          "id":"b026e489a41f4c73bae9c2efba6bed07",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":457,
              "y":568},
            "size":{
              "width":57,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f31b5528f0542288a0e90db1c6a50d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":457,
                  "y":568},
                "size":{
                  "width":57,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3064a4a4518e4502b8534a4d883122c3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":515,
              "y":566},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0c60ac3955db468896976133588dff3d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":568,
              "y":594},
            "size":{
              "width":40,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66ca6cfcfe4f4c2fb3b34813571277f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":568,
                  "y":594},
                "size":{
                  "width":40,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/酒店地面价格设置/u47.png"}},
{
          "id":"d82484414735461a8e47cc173799b3e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":458,
              "y":602},
            "size":{
              "width":57,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a91016a2440d4e969d724f0b63325375",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":458,
                  "y":602},
                "size":{
                  "width":57,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34fa2c197c3f4477857d746b76a19f53",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":516,
              "y":600},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"dd91cf0e82a44c9e8fb4daaba62d6607",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":568,
              "y":632},
            "size":{
              "width":40,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4322578852a4c1f8afc9cdacc792969",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":568,
                  "y":632},
                "size":{
                  "width":40,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/酒店地面价格设置/u47.png"}},
{
          "id":"2eba564931a3456db5fe87370252e3a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":458,
              "y":640},
            "size":{
              "width":57,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbc5e902d78c4867a7efc2545b38998e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":458,
                  "y":640},
                "size":{
                  "width":57,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8efbb44b14604f58a7bfd9ef68b55190",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":516,
              "y":638},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ef066ed8018a4b03af1ef9c26bb08066",
          "label":"交通套餐ID",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":200,
              "y":530},
            "size":{
              "width":94,
              "height":26},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfe63ae771394eeca7b1e74c7786a369",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":200,
                  "y":530},
                "size":{
                  "width":94,
                  "height":26},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65af2a1f4868418e9692868baead6bae",
          "label":"txt交通套餐ID",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "location":{
              "x":320,
              "y":530},
            "size":{
              "width":127,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"514af2fdb62d45b0ada8f65a11f4864d",
          "label":"交通套餐+",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":567,
              "y":520},
            "size":{
              "width":40,
              "height":35},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5eba00d6bb442009d3cdaf0cb904e86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":567,
                  "y":520},
                "size":{
                  "width":40,
                  "height":35},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/酒店地面价格设置/u47.png"}},
{
          "id":"b9575fefe7294284b8d6eaa0555ee0c3",
          "label":"交通套餐份数",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":457,
              "y":530},
            "size":{
              "width":57,
              "height":26},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0734292cd8c0466c8ce4960b42e55071",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":457,
                  "y":530},
                "size":{
                  "width":57,
                  "height":26},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89a2cb5ca15e43e6a76fac1769d51874",
          "label":"txt交通套餐份数",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "location":{
              "x":515,
              "y":530},
            "size":{
              "width":40,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"17a857de6837466cb368c80b8bbc51c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":228,
              "y":678},
            "size":{
              "width":94,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49953ed79b5f4d0e8d75fd3819eb81f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":228,
                  "y":678},
                "size":{
                  "width":94,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b52c0975342f44b586a167a111708a7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":228,
              "y":709},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8598ee2457fe4416b4f476e36b0e700d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":228,
                  "y":709},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b523bd9526742deb58e7d31fb92f9bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":228,
              "y":741},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d245c8aa13894d378ccda81db665d946",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":228,
                  "y":741},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"504750e3802e4e1c814aba31f744dc85",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":443,
              "y":675},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e5276ce1be84f73a730afc7137606ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":443,
                  "y":675},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d0216feed084377b8613b9c2b6f2799",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":450,
              "y":710},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68a53e5d58d44607aa6063f5693770af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":450,
                  "y":710},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4354fdc7fef407b8875725aa78b9185",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":451,
              "y":742},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"401f528205aa4ebeaa42d8e120193f80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":451,
                  "y":742},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b20379304bd498c84b405a2b0dac45e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":193,
              "y":796},
            "size":{
              "width":540,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa128daf332c429baeea7df257c2fab2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":193,
                  "y":796},
                "size":{
                  "width":540,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "c0a6f8e65f9843a4bd1f1d0f4546bc5c":{
      "packageId":"c0a6f8e65f9843a4bd1f1d0f4546bc5c",
      "type":"Axure:Master",
      "name":"产品管理",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"5024326008c74a3f90f4004ca3eb09ad",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":1364,
                "height":667}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3533708ddaf64d53ab22ac58fbcf7457",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1364,
                    "height":667}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/酒店/u1.png"}},
{
            "id":"b3d7ad7f6d44402fbfdfac4c0f1e8cb0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":140,
                "y":76},
              "size":{
                "width":1226,
                "height":591},
              "linePattern":"none"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b3e89a31a0f041cbbc6ef6f867f6e9ca",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":140,
                    "y":76},
                  "size":{
                    "width":1226,
                    "height":591},
                  "linePattern":"none"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/酒店/u3.png"}}]}}},
  "objectPaths":{
    "c4b2ade6f2324efb91ff708b10ce0066":{
      "scriptId":"u0",
      "5024326008c74a3f90f4004ca3eb09ad":{
        "scriptId":"u1"},
      "3533708ddaf64d53ab22ac58fbcf7457":{
        "scriptId":"u2"},
      "b3d7ad7f6d44402fbfdfac4c0f1e8cb0":{
        "scriptId":"u3"},
      "b3e89a31a0f041cbbc6ef6f867f6e9ca":{
        "scriptId":"u4"}},
    "fb216cbb84f046a6b0026e2db2e6b03f":{
      "scriptId":"u5"},
    "be051d042d834166bfe5a3ba62ce26e3":{
      "scriptId":"u6"},
    "44e4aa2661c94b96940fd7b63dd0be33":{
      "scriptId":"u7"},
    "ecf930680d8c4c0690e0abe24f29a0b7":{
      "scriptId":"u8"},
    "e84798ae147a4785a222f5d8e7a61a6d":{
      "scriptId":"u9"},
    "65be1afbe8c248c4a217f65d469e6439":{
      "scriptId":"u10"},
    "8f4f20abfaec44b299cd8dd9d154e124":{
      "scriptId":"u11"},
    "c2f8c4a434f3433ba6ebfddde380118a":{
      "scriptId":"u12"},
    "dd984f08b4044412b7ebbe2f9d273a8e":{
      "scriptId":"u13"},
    "7689b522b60b48dd8606bb41d821ddba":{
      "scriptId":"u14"},
    "5c33778c7b1e4e44a18ea4154ac23790":{
      "scriptId":"u15"},
    "51fc89f017ce4efd97d285dd98019a08":{
      "scriptId":"u16"},
    "1ff8692b0bbb4bbfacf7d17f685f29bd":{
      "scriptId":"u17"},
    "67a8a9923ffd4585b228f7ef405346e6":{
      "scriptId":"u18"},
    "49132108e61341d08665c68da65bf193":{
      "scriptId":"u19"},
    "3d7dcb11956d4ab08566ace7463a6703":{
      "scriptId":"u20"},
    "cf9fdb25032542098a43f420c43ce688":{
      "scriptId":"u21"},
    "8266bd983b3c4e0c8d121760319c7f80":{
      "scriptId":"u22"},
    "41cb9e2b5a9c4c649b11351103bafd6b":{
      "scriptId":"u23"},
    "1627c71f299343f0b1c689097cfc623d":{
      "scriptId":"u24"},
    "272483bfb60c4a918ba33d40336960af":{
      "scriptId":"u25"},
    "8b970aa9d0aa4dd0a3a0a3618ecf7ecd":{
      "scriptId":"u26"},
    "daa42c111f5544f9b0681139b0c3abde":{
      "scriptId":"u27"},
    "a5c19d1e5cfd4839925500724db98a4f":{
      "scriptId":"u28"},
    "7d6626ce535840abb881be0d790bb0bd":{
      "scriptId":"u29"},
    "6566508598424bc4b064727cd108ea8d":{
      "scriptId":"u30"},
    "19fb21dcc1204802baf75f4c1741dd49":{
      "scriptId":"u31"},
    "6800653212174311ac0af6aafe135830":{
      "scriptId":"u32"},
    "f97a1c72d9fa43b39fe2bcefe1f69eb2":{
      "scriptId":"u33"},
    "e6e214f6133049dbb524460fff80872a":{
      "scriptId":"u34"},
    "71296753004b4981ac60d282c6e38c51":{
      "scriptId":"u35"},
    "e7c3e068147b46b3a3008a476a327b44":{
      "scriptId":"u36"},
    "08c28e1ec67e42818240839b94838bb1":{
      "scriptId":"u37"},
    "909a0bbf72e0444189c8a1c1f7705e0e":{
      "scriptId":"u38"},
    "18ddbbd327d84fcfbb221e2b54d21efb":{
      "scriptId":"u39"},
    "38f218813a3e4364b6186011817a7457":{
      "scriptId":"u40"},
    "41a3f5677ef846adb2f1576c2b43020d":{
      "scriptId":"u41"},
    "4b48445ca0d446e5aaca9c14ec868913":{
      "scriptId":"u42"},
    "37ceb600ad7c4bef98150fbc62f6623b":{
      "scriptId":"u43"},
    "32e16c4bb2fb48868775f4ae096ee9ce":{
      "scriptId":"u44"},
    "495b773dfdad4a7ca13b75c531c697b0":{
      "scriptId":"u45"},
    "e1dc3b8fcbe54e2a938042f7d80fb5f5":{
      "scriptId":"u46"},
    "6980c726e96e474ab985d82cdd13061e":{
      "scriptId":"u47"},
    "9d53d3bcca0e48e0b09078d5d7235bee":{
      "scriptId":"u48"},
    "90932bc715a647e9a127f539a8366951":{
      "scriptId":"u49"},
    "0631c197643a43cd812ee2ee66d27b93":{
      "scriptId":"u50"},
    "ee61d2dc493d433d89afd8af84dc0f4a":{
      "scriptId":"u51"},
    "d5d8ad6628ea4da1adc4a950e00c7eb7":{
      "scriptId":"u52"},
    "91b207a0ce374dc1b2b39ed335223739":{
      "scriptId":"u53"},
    "b026e489a41f4c73bae9c2efba6bed07":{
      "scriptId":"u54"},
    "3f31b5528f0542288a0e90db1c6a50d2":{
      "scriptId":"u55"},
    "3064a4a4518e4502b8534a4d883122c3":{
      "scriptId":"u56"},
    "0c60ac3955db468896976133588dff3d":{
      "scriptId":"u57"},
    "66ca6cfcfe4f4c2fb3b34813571277f9":{
      "scriptId":"u58"},
    "d82484414735461a8e47cc173799b3e7":{
      "scriptId":"u59"},
    "a91016a2440d4e969d724f0b63325375":{
      "scriptId":"u60"},
    "34fa2c197c3f4477857d746b76a19f53":{
      "scriptId":"u61"},
    "dd91cf0e82a44c9e8fb4daaba62d6607":{
      "scriptId":"u62"},
    "a4322578852a4c1f8afc9cdacc792969":{
      "scriptId":"u63"},
    "2eba564931a3456db5fe87370252e3a8":{
      "scriptId":"u64"},
    "fbc5e902d78c4867a7efc2545b38998e":{
      "scriptId":"u65"},
    "8efbb44b14604f58a7bfd9ef68b55190":{
      "scriptId":"u66"},
    "ef066ed8018a4b03af1ef9c26bb08066":{
      "scriptId":"u67"},
    "cfe63ae771394eeca7b1e74c7786a369":{
      "scriptId":"u68"},
    "65af2a1f4868418e9692868baead6bae":{
      "scriptId":"u69"},
    "514af2fdb62d45b0ada8f65a11f4864d":{
      "scriptId":"u70"},
    "c5eba00d6bb442009d3cdaf0cb904e86":{
      "scriptId":"u71"},
    "b9575fefe7294284b8d6eaa0555ee0c3":{
      "scriptId":"u72"},
    "0734292cd8c0466c8ce4960b42e55071":{
      "scriptId":"u73"},
    "89a2cb5ca15e43e6a76fac1769d51874":{
      "scriptId":"u74"},
    "17a857de6837466cb368c80b8bbc51c7":{
      "scriptId":"u75"},
    "49953ed79b5f4d0e8d75fd3819eb81f4":{
      "scriptId":"u76"},
    "b52c0975342f44b586a167a111708a7e":{
      "scriptId":"u77"},
    "8598ee2457fe4416b4f476e36b0e700d":{
      "scriptId":"u78"},
    "6b523bd9526742deb58e7d31fb92f9bd":{
      "scriptId":"u79"},
    "d245c8aa13894d378ccda81db665d946":{
      "scriptId":"u80"},
    "504750e3802e4e1c814aba31f744dc85":{
      "scriptId":"u81"},
    "8e5276ce1be84f73a730afc7137606ef":{
      "scriptId":"u82"},
    "1d0216feed084377b8613b9c2b6f2799":{
      "scriptId":"u83"},
    "68a53e5d58d44607aa6063f5693770af":{
      "scriptId":"u84"},
    "b4354fdc7fef407b8875725aa78b9185":{
      "scriptId":"u85"},
    "401f528205aa4ebeaa42d8e120193f80":{
      "scriptId":"u86"},
    "2b20379304bd498c84b405a2b0dac45e":{
      "scriptId":"u87"},
    "aa128daf332c429baeea7df257c2fab2":{
      "scriptId":"u88"}}});