$axure.loadCurrentPage({
  "url":"预订订单.html",
  "generationDate":new Date(1419937542825.89),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ac36843d6ec74e858091ca06d064a6fe",
    "type":"Axure:Page",
    "name":"预订订单",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"71e7848689b14dd8bd604f8f0b6bc22e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1364,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"480d95ecdf1e4213962de1354dc81b53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1364,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品列表/u0.png"}},
{
          "id":"c87d60df23ca4f46b744cf5bb5e4af89",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":144,
              "y":210},
            "size":{
              "width":1196,
              "height":451},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43ce6852fb9644c3be01f62944670933",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":144,
                  "y":210},
                "size":{
                  "width":1196,
                  "height":451},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预订订单/u2.png"}},
{
          "id":"a89137e8ec2a4ef4b0a294155e732227",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEAF0F7},
            "location":{
              "x":150,
              "y":240},
            "size":{
              "width":1150,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD5DFE8}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2818aec616234d7b90a0af632294d4b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEAF0F7},
                "location":{
                  "x":150,
                  "y":240},
                "size":{
                  "width":1150,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD5DFE8}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预订订单/u4.png"}},
{
          "id":"242ff2541b9548dcaf5c93a65201e92d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5252F2,
              "opacity":1},
            "location":{
              "x":190,
              "y":252},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55f1d6b188ba4dbfae9a3adcf93e3d70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF5252F2,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":252},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"157952dee3064765aa5dd1cf5bb0b816",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5252F2,
              "opacity":1},
            "location":{
              "x":390,
              "y":252},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"781149b432464ac6aae80da8f7336207",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF5252F2,
                  "opacity":1},
                "location":{
                  "x":390,
                  "y":252},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d347c88d201d45f19213f5c8b308a69b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5252F2,
              "opacity":1},
            "location":{
              "x":570,
              "y":252},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b055a0f41ae94ea08337aa97843b6ceb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF5252F2,
                  "opacity":1},
                "location":{
                  "x":570,
                  "y":252},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db230885034e4b88aa8a7f7a15b0dfc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5252F2,
              "opacity":1},
            "location":{
              "x":660,
              "y":252},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff3e815bdc0b4acd8bcfa142fdce7d7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF5252F2,
                  "opacity":1},
                "location":{
                  "x":660,
                  "y":252},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7dff7cfdf2204131bdace855b0354cc5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":279},
            "size":{
              "width":1150,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD5DFE8}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a31d70b9ed343e1a217edfeb3908f63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":279},
                "size":{
                  "width":1150,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD5DFE8}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预订订单/u14.png"}},
{
          "id":"f21d392c1d034d7ea64589381d878f78",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":290},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a149a4dc8f944aeb638afc727cbdbbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":290},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34dc7d7b995b4668a6adea44cfae5973",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5252F2,
              "opacity":1},
            "location":{
              "x":260,
              "y":252},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35b43e7ab7454517861272d8a2f19b35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF5252F2,
                  "opacity":1},
                "location":{
                  "x":260,
                  "y":252},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0da11c98ae4d4804aac7b160093b899d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":290},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3f79dfb20d6480bbbad2d2fc69620d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":290},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1a3ab851ca0422892dfcbb29c695d43",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":326,
              "y":290},
            "size":{
              "width":220,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"797858d8b76f4183bb315e3e4905edab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":326,
                  "y":290},
                "size":{
                  "width":220,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10a8f3a74e5848c49b9335f3d162e4fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":290},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5a6a55629e5452795251e01c0a04490",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":290},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0166ab4406be4933af4a9d622f6c990f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":660,
              "y":290},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5382c87b642549b3a5855db4aef4b400",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":660,
                  "y":290},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"521d6373071343f3a72f5809c19a39c8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":285.5},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 信息填写",
                      "target":{
                        "targetType":"page",
                        "url":"信息填写.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"bafca7cbefd84ceeb5536ad928533661",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":318},
            "size":{
              "width":1150,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD5DFE8}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b8f140bbdbc4b41892a5f741611f231",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":318},
                "size":{
                  "width":1150,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD5DFE8}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预订订单/u14.png"}},
{
          "id":"a7fd9bad1328412896c1a5d0ead87993",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":329},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16b06d8b1a5741c586d54e86c746cf3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":329},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3455228ab244e56963f9e696afde7d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":329},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1422463305f44f4995b8d1faa827b9ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":329},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8dfe5c58c8fa495cbf9e93bafbb7e58f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":326,
              "y":329},
            "size":{
              "width":220,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38095a96a295458ca3b0bf428dce6402",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":326,
                  "y":329},
                "size":{
                  "width":220,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56075efba2a84f4e90c43eeef146d336",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":329},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ee5151eef254f79985bc84665a282a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":329},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"17fdaadff9674627951909352f8305f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":660,
              "y":329},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"354848c8d7914ea2b2f20150e991deff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":660,
                  "y":329},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"039db5e5e3b447a092c261995ad50559",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":325},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "71e7848689b14dd8bd604f8f0b6bc22e":{
      "scriptId":"u0"},
    "480d95ecdf1e4213962de1354dc81b53":{
      "scriptId":"u1"},
    "c87d60df23ca4f46b744cf5bb5e4af89":{
      "scriptId":"u2"},
    "43ce6852fb9644c3be01f62944670933":{
      "scriptId":"u3"},
    "a89137e8ec2a4ef4b0a294155e732227":{
      "scriptId":"u4"},
    "2818aec616234d7b90a0af632294d4b2":{
      "scriptId":"u5"},
    "242ff2541b9548dcaf5c93a65201e92d":{
      "scriptId":"u6"},
    "55f1d6b188ba4dbfae9a3adcf93e3d70":{
      "scriptId":"u7"},
    "157952dee3064765aa5dd1cf5bb0b816":{
      "scriptId":"u8"},
    "781149b432464ac6aae80da8f7336207":{
      "scriptId":"u9"},
    "d347c88d201d45f19213f5c8b308a69b":{
      "scriptId":"u10"},
    "b055a0f41ae94ea08337aa97843b6ceb":{
      "scriptId":"u11"},
    "db230885034e4b88aa8a7f7a15b0dfc8":{
      "scriptId":"u12"},
    "ff3e815bdc0b4acd8bcfa142fdce7d7d":{
      "scriptId":"u13"},
    "7dff7cfdf2204131bdace855b0354cc5":{
      "scriptId":"u14"},
    "3a31d70b9ed343e1a217edfeb3908f63":{
      "scriptId":"u15"},
    "f21d392c1d034d7ea64589381d878f78":{
      "scriptId":"u16"},
    "5a149a4dc8f944aeb638afc727cbdbbd":{
      "scriptId":"u17"},
    "34dc7d7b995b4668a6adea44cfae5973":{
      "scriptId":"u18"},
    "35b43e7ab7454517861272d8a2f19b35":{
      "scriptId":"u19"},
    "0da11c98ae4d4804aac7b160093b899d":{
      "scriptId":"u20"},
    "d3f79dfb20d6480bbbad2d2fc69620d6":{
      "scriptId":"u21"},
    "a1a3ab851ca0422892dfcbb29c695d43":{
      "scriptId":"u22"},
    "797858d8b76f4183bb315e3e4905edab":{
      "scriptId":"u23"},
    "10a8f3a74e5848c49b9335f3d162e4fa":{
      "scriptId":"u24"},
    "d5a6a55629e5452795251e01c0a04490":{
      "scriptId":"u25"},
    "0166ab4406be4933af4a9d622f6c990f":{
      "scriptId":"u26"},
    "5382c87b642549b3a5855db4aef4b400":{
      "scriptId":"u27"},
    "521d6373071343f3a72f5809c19a39c8":{
      "scriptId":"u28"},
    "bafca7cbefd84ceeb5536ad928533661":{
      "scriptId":"u29"},
    "9b8f140bbdbc4b41892a5f741611f231":{
      "scriptId":"u30"},
    "a7fd9bad1328412896c1a5d0ead87993":{
      "scriptId":"u31"},
    "16b06d8b1a5741c586d54e86c746cf3f":{
      "scriptId":"u32"},
    "c3455228ab244e56963f9e696afde7d4":{
      "scriptId":"u33"},
    "1422463305f44f4995b8d1faa827b9ba":{
      "scriptId":"u34"},
    "8dfe5c58c8fa495cbf9e93bafbb7e58f":{
      "scriptId":"u35"},
    "38095a96a295458ca3b0bf428dce6402":{
      "scriptId":"u36"},
    "56075efba2a84f4e90c43eeef146d336":{
      "scriptId":"u37"},
    "5ee5151eef254f79985bc84665a282a8":{
      "scriptId":"u38"},
    "17fdaadff9674627951909352f8305f5":{
      "scriptId":"u39"},
    "354848c8d7914ea2b2f20150e991deff":{
      "scriptId":"u40"},
    "039db5e5e3b447a092c261995ad50559":{
      "scriptId":"u41"}}});