$axure.loadCurrentPage({
  "url":"供应商开户.html",
  "generationDate":new Date(1419937543175.91),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e361fb071b404e098b7da4b862e383b6",
    "type":"Axure:Page",
    "name":"供应商开户",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f2f27a23296f4eeeb0040ad2ea843fba",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"2e9faf354c90439e96053dcd947b4c04"},
{
          "id":"3bc6b59ea27949d1abad7fcd632ad9b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3A6EA5,
              "opacity":1},
            "location":{
              "x":20,
              "y":56},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4db06158c9324669aea22bc4a0b49d13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3A6EA5,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":56},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e812a0306e594311b8157e6383c17a63",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3A6EA5,
              "opacity":1},
            "location":{
              "x":40,
              "y":100},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e4e5ad82a60459da6d39576cff5b968",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3A6EA5,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":100},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3340ae7babd4ff79174a542e878a33f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":249,
              "y":56},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"791b035987914b9ab4f0dea986e3cec5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":249,
                  "y":56},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29129e8ede8d46cdb439376da6bcb816",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":167.5,
              "y":90},
            "size":{
              "width":725,
              "height":494}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"851bef1ad8ce4c6c91cab5c0725a0484",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":167.5,
                  "y":90},
                "size":{
                  "width":725,
                  "height":494}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商开户/u46.png"}},
{
          "id":"44c22010c79e4d9cabeda2fc8c60ad35",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":174,
              "y":578},
            "size":{
              "width":718,
              "height":52},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4112de8b2db041b99617ea05ced0d224",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":174,
                  "y":578},
                "size":{
                  "width":718,
                  "height":52},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商开户/u48.png"}},
{
          "id":"277113658f634063b3970f5d3620d7df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":211,
              "y":596},
            "size":{
              "width":109,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3c19cd5bdaf423b9acb486b9c40fa7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":211,
                  "y":596},
                "size":{
                  "width":109,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f7884b46d6b474f9ed21a033cbf81f5",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":593},
            "size":{
              "width":250,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ca8ab2136f144045b3ff0a7ee6566faf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":174,
              "y":625},
            "size":{
              "width":718,
              "height":52},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64f1c1611e3242d9913ce88a3e7ee1aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":174,
                  "y":625},
                "size":{
                  "width":718,
                  "height":52},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商开户/u48.png"}},
{
          "id":"07c8aeb0add84e32b8952abd61d6fa7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":206,
              "y":646},
            "size":{
              "width":109,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa4a6f43e04a4ff995aa17591950c128",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":206,
                  "y":646},
                "size":{
                  "width":109,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05e28ba709d940d9bc53d04b976e8054",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":646},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e039c19da61459c87cbea6e87582978",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":646},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"01d3b3b0556d4b81aa70604597feb685",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":393,
              "y":646},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0e59f48d65e4b009b24f82325709b45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":393,
                  "y":646},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"ed93a79f50bc41db815d912c10b70781",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":319,
              "y":688},
            "size":{
              "width":72,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5854d4d6a5b42a29e502787c2d392c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":319,
                  "y":688},
                "size":{
                  "width":72,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商开户/u61.png"}}]}},
  "masters":{
    "2e9faf354c90439e96053dcd947b4c04":{
      "packageId":"2e9faf354c90439e96053dcd947b4c04",
      "type":"Axure:Master",
      "name":"公共",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"73664c8f10954464a54775f24fbf35d0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF3A6EA5},
              "size":{
                "width":1050,
                "height":49},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c8a3f258d2bd4d939ba4fbfcffc76dc2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF3A6EA5},
                  "size":{
                    "width":1050,
                    "height":49},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/供应商开户/u1.png"}},
{
            "id":"bfb6e9e6e25c4e84a7816ee55c8dccc4",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":122,
                "height":49}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cc97cc53525b417bb2f7d0d3fd3e9fd1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":122,
                    "height":49}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/供应商开户/u3.png"}},
{
            "id":"1d1454bfdbbf477bb62077cad5a02323",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":163,
                "y":18},
              "size":{
                "width":87,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bed98ef0ed9f4acfb04e586e76096fb7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":163,
                    "y":18},
                  "size":{
                    "width":87,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/供应商开户/u5.png"}},
{
            "id":"f32bb7b4e0724c7cac21e1636ef43ca4",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":263,
                "y":18},
              "size":{
                "width":87,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b980461bf8904da0a51e649b6a4e2094",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":263,
                    "y":18},
                  "size":{
                    "width":87,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/供应商开户/u5.png"}},
{
            "id":"fea38d5cdb724da0864f899b9987cf57",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":485,
                "y":19},
              "size":{
                "width":85,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"55f0051fb5e840ceb0d3ae9edf670a82",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":485,
                    "y":19},
                  "size":{
                    "width":85,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/供应商开户/u9.png"}},
{
            "id":"7d72e4bc3027484f9b4986b200f5dcbc",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF7FBFC},
              "location":{
                "x":-10,
                "y":49},
              "size":{
                "width":150,
                "height":801},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD5DEE3}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ef10ab382a924b949e28077410329d09",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF7FBFC},
                  "location":{
                    "x":-10,
                    "y":49},
                  "size":{
                    "width":150,
                    "height":801},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD5DEE3}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/供应商开户/u11.png"}},
{
            "id":"07698ac0b3da4174811bd1d0b92b3d35",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":74},
              "size":{
                "width":130,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD5DEE3}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/供应商开户/u13_line.png"}},
{
            "id":"af1de0d9981445cbad361f269328d74d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":115,
                "y":57},
              "size":{
                "width":13,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6c6921f3c6f74822b6e4cd289fcaffdc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":115,
                    "y":57},
                  "size":{
                    "width":13,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/供应商开户/u14.png"}},
{
            "id":"01b02d22d1b340d5b4abeaa0a3514eee",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":3,
                "y":90},
              "size":{
                "width":130,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2eb3d8aa2af5417ebd2dfeafc87e6cd6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":3,
                    "y":90},
                  "size":{
                    "width":130,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/供应商开户/u16.png"}},
{
            "id":"41988162a80548cd8f1441d91b6617be",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFEBEFEF},
              "location":{
                "x":139,
                "y":49},
              "size":{
                "width":911,
                "height":801},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD5DEE3}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0b506cf9b0af49c78227ffd3bcef428b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFEBEFEF},
                  "location":{
                    "x":139,
                    "y":49},
                  "size":{
                    "width":911,
                    "height":801},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD5DEE3}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/供应商开户/u18.png"}},
{
            "id":"bda841a3d4d14dc9a0c35d6c37418af4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":149,
                "y":78},
              "size":{
                "width":901,
                "height":762},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD5DEE3}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"33dc2077939f44edbe4a82b4e6981047",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":149,
                    "y":78},
                  "size":{
                    "width":901,
                    "height":762},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD5DEE3}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/供应商开户/u20.png"}},
{
            "id":"5d9a705a4501475ca6294cd7e6619356",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":139,
                "y":54},
              "size":{
                "width":15,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2d17f59e6daf429baf4eeeffcf8b4c79",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":139,
                    "y":54},
                  "size":{
                    "width":15,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/供应商开户/u22.png"}},
{
            "id":"2edc8b92c547404fb17f4e746a0b73bb",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":143,
                "y":308},
              "size":{
                "width":6,
                "height":18}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7dd5c667faee4590a6e4a8049d064dbe",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":143,
                    "y":308},
                  "size":{
                    "width":6,
                    "height":18}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/供应商开户/u24.png"}},
{
            "id":"86f14912664740a1be9414b2f7ec2841",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontSize":"15px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":181,
                "y":29},
              "size":{
                "width":60,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cabbedab85f44ff38eafd2b28ce739b2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontSize":"15px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":181,
                    "y":29},
                  "size":{
                    "width":60,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"55fa024d4ec94021bebc166a5d6fafc2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontSize":"15px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":275,
                "y":29},
              "size":{
                "width":60,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e0bb3a719dee4ef9a74cb74a33da0a9c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontSize":"15px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":275,
                    "y":29},
                  "size":{
                    "width":60,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e9b191bbe5c44deaba5f09a0daed0ac9",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":370,
                "y":18},
              "size":{
                "width":87,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8e0ae7fab6be480f98c5f2dc7ae70cd4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":370,
                    "y":18},
                  "size":{
                    "width":87,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/供应商开户/u5.png"}},
{
            "id":"315d1cf834ef40bc993e6a6bbfa32120",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontSize":"15px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":382,
                "y":29},
              "size":{
                "width":60,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"71755fda1c7b4a92a95d6a0c3d985cb1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontSize":"15px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":382,
                    "y":29},
                  "size":{
                    "width":60,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5a71d92f301f44e7b3b0bf75be981ba0",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontSize":"15px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF3A6EA5,
                "opacity":1},
              "location":{
                "x":501,
                "y":29},
              "size":{
                "width":60,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"49edfdc39c90485189066540e7efd635",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontSize":"15px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF3A6EA5,
                    "opacity":1},
                  "location":{
                    "x":501,
                    "y":29},
                  "size":{
                    "width":60,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"a47f04adb4a6418380f8db34f960a3c0",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":164,
                "y":56},
              "size":{
                "width":60,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"30b16fb847d34546b138a5de5e2ab09a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":164,
                    "y":56},
                  "size":{
                    "width":60,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7dcff270b5ca46b28308ddf332064d46",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF89A5EA},
              "location":{
                "x":227,
                "y":49},
              "size":{
                "width":121,
                "height":29},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6cdcf7cfb91340b6b019b19f6c1e3922",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF89A5EA},
                  "location":{
                    "x":227,
                    "y":49},
                  "size":{
                    "width":121,
                    "height":29},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/供应商开户/u38.png"}}]}}},
  "objectPaths":{
    "f2f27a23296f4eeeb0040ad2ea843fba":{
      "scriptId":"u0",
      "73664c8f10954464a54775f24fbf35d0":{
        "scriptId":"u1"},
      "c8a3f258d2bd4d939ba4fbfcffc76dc2":{
        "scriptId":"u2"},
      "bfb6e9e6e25c4e84a7816ee55c8dccc4":{
        "scriptId":"u3"},
      "cc97cc53525b417bb2f7d0d3fd3e9fd1":{
        "scriptId":"u4"},
      "1d1454bfdbbf477bb62077cad5a02323":{
        "scriptId":"u5"},
      "bed98ef0ed9f4acfb04e586e76096fb7":{
        "scriptId":"u6"},
      "f32bb7b4e0724c7cac21e1636ef43ca4":{
        "scriptId":"u7"},
      "b980461bf8904da0a51e649b6a4e2094":{
        "scriptId":"u8"},
      "fea38d5cdb724da0864f899b9987cf57":{
        "scriptId":"u9"},
      "55f0051fb5e840ceb0d3ae9edf670a82":{
        "scriptId":"u10"},
      "7d72e4bc3027484f9b4986b200f5dcbc":{
        "scriptId":"u11"},
      "ef10ab382a924b949e28077410329d09":{
        "scriptId":"u12"},
      "07698ac0b3da4174811bd1d0b92b3d35":{
        "scriptId":"u13"},
      "af1de0d9981445cbad361f269328d74d":{
        "scriptId":"u14"},
      "6c6921f3c6f74822b6e4cd289fcaffdc":{
        "scriptId":"u15"},
      "01b02d22d1b340d5b4abeaa0a3514eee":{
        "scriptId":"u16"},
      "2eb3d8aa2af5417ebd2dfeafc87e6cd6":{
        "scriptId":"u17"},
      "41988162a80548cd8f1441d91b6617be":{
        "scriptId":"u18"},
      "0b506cf9b0af49c78227ffd3bcef428b":{
        "scriptId":"u19"},
      "bda841a3d4d14dc9a0c35d6c37418af4":{
        "scriptId":"u20"},
      "33dc2077939f44edbe4a82b4e6981047":{
        "scriptId":"u21"},
      "5d9a705a4501475ca6294cd7e6619356":{
        "scriptId":"u22"},
      "2d17f59e6daf429baf4eeeffcf8b4c79":{
        "scriptId":"u23"},
      "2edc8b92c547404fb17f4e746a0b73bb":{
        "scriptId":"u24"},
      "7dd5c667faee4590a6e4a8049d064dbe":{
        "scriptId":"u25"},
      "86f14912664740a1be9414b2f7ec2841":{
        "scriptId":"u26"},
      "cabbedab85f44ff38eafd2b28ce739b2":{
        "scriptId":"u27"},
      "55fa024d4ec94021bebc166a5d6fafc2":{
        "scriptId":"u28"},
      "e0bb3a719dee4ef9a74cb74a33da0a9c":{
        "scriptId":"u29"},
      "e9b191bbe5c44deaba5f09a0daed0ac9":{
        "scriptId":"u30"},
      "8e0ae7fab6be480f98c5f2dc7ae70cd4":{
        "scriptId":"u31"},
      "315d1cf834ef40bc993e6a6bbfa32120":{
        "scriptId":"u32"},
      "71755fda1c7b4a92a95d6a0c3d985cb1":{
        "scriptId":"u33"},
      "5a71d92f301f44e7b3b0bf75be981ba0":{
        "scriptId":"u34"},
      "49edfdc39c90485189066540e7efd635":{
        "scriptId":"u35"},
      "a47f04adb4a6418380f8db34f960a3c0":{
        "scriptId":"u36"},
      "30b16fb847d34546b138a5de5e2ab09a":{
        "scriptId":"u37"},
      "7dcff270b5ca46b28308ddf332064d46":{
        "scriptId":"u38"},
      "6cdcf7cfb91340b6b019b19f6c1e3922":{
        "scriptId":"u39"}},
    "3bc6b59ea27949d1abad7fcd632ad9b1":{
      "scriptId":"u40"},
    "4db06158c9324669aea22bc4a0b49d13":{
      "scriptId":"u41"},
    "e812a0306e594311b8157e6383c17a63":{
      "scriptId":"u42"},
    "3e4e5ad82a60459da6d39576cff5b968":{
      "scriptId":"u43"},
    "c3340ae7babd4ff79174a542e878a33f":{
      "scriptId":"u44"},
    "791b035987914b9ab4f0dea986e3cec5":{
      "scriptId":"u45"},
    "29129e8ede8d46cdb439376da6bcb816":{
      "scriptId":"u46"},
    "851bef1ad8ce4c6c91cab5c0725a0484":{
      "scriptId":"u47"},
    "44c22010c79e4d9cabeda2fc8c60ad35":{
      "scriptId":"u48"},
    "4112de8b2db041b99617ea05ced0d224":{
      "scriptId":"u49"},
    "277113658f634063b3970f5d3620d7df":{
      "scriptId":"u50"},
    "f3c19cd5bdaf423b9acb486b9c40fa7a":{
      "scriptId":"u51"},
    "0f7884b46d6b474f9ed21a033cbf81f5":{
      "scriptId":"u52"},
    "ca8ab2136f144045b3ff0a7ee6566faf":{
      "scriptId":"u53"},
    "64f1c1611e3242d9913ce88a3e7ee1aa":{
      "scriptId":"u54"},
    "07c8aeb0add84e32b8952abd61d6fa7a":{
      "scriptId":"u55"},
    "aa4a6f43e04a4ff995aa17591950c128":{
      "scriptId":"u56"},
    "05e28ba709d940d9bc53d04b976e8054":{
      "scriptId":"u57"},
    "6e039c19da61459c87cbea6e87582978":{
      "scriptId":"u58"},
    "01d3b3b0556d4b81aa70604597feb685":{
      "scriptId":"u59"},
    "c0e59f48d65e4b009b24f82325709b45":{
      "scriptId":"u60"},
    "ed93a79f50bc41db815d912c10b70781":{
      "scriptId":"u61"},
    "d5854d4d6a5b42a29e502787c2d392c5":{
      "scriptId":"u62"}}});