$axure.loadCurrentPage({
  "url":"包车.html",
  "generationDate":new Date(1419937539546.7),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1d07c80bd5e5411faba2ac35f987957c",
    "type":"Axure:Page",
    "name":"包车",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"63dd5c6754a744d186f783036e6bc07d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"c0a6f8e65f9843a4bd1f1d0f4546bc5c"},
{
          "id":"9fbd82dc4fc3434783ae7224ba6f6079",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":85},
            "size":{
              "width":1194,
              "height":552}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3f2de8aa3e541e6a5df15b00e44f221",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":85},
                "size":{
                  "width":1194,
                  "height":552}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/包车/u5.png"}},
{
          "id":"5dc9f5bf1b4e4153bf5daeb426193b09",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":153,
              "y":461},
            "size":{
              "width":1188,
              "height":178}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f34af4bf3a742da8a0655777ed30254",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":153,
                  "y":461},
                "size":{
                  "width":1188,
                  "height":178}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/包车/u7.png"}},
{
          "id":"adaab992049047c9a290cd3450ec493e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":153,
              "y":631},
            "size":{
              "width":1189,
              "height":272}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6ed3ec0b094468e923bca41215e0c7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":153,
                  "y":631},
                "size":{
                  "width":1189,
                  "height":272}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/包车/u9.png"}},
{
          "id":"ffd6f994c68e4f2d98ebbb94703662e9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":332,
              "y":732},
            "size":{
              "width":664,
              "height":194}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a67a0ee2571646988e965983981abc68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":332,
                  "y":732},
                "size":{
                  "width":664,
                  "height":194}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/包车/u11.png"}},
{
          "id":"2a098fbf6a59436f857480e1e2ca1e7b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":153,
              "y":929},
            "size":{
              "width":1189,
              "height":468}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a0375a7508846f594f9291e36a9cd94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":153,
                  "y":929},
                "size":{
                  "width":1189,
                  "height":468}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/包车/u13.png"}}]}},
  "masters":{
    "c0a6f8e65f9843a4bd1f1d0f4546bc5c":{
      "packageId":"c0a6f8e65f9843a4bd1f1d0f4546bc5c",
      "type":"Axure:Master",
      "name":"产品管理",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"5024326008c74a3f90f4004ca3eb09ad",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":1364,
                "height":667}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3533708ddaf64d53ab22ac58fbcf7457",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1364,
                    "height":667}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/酒店/u1.png"}},
{
            "id":"b3d7ad7f6d44402fbfdfac4c0f1e8cb0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":140,
                "y":76},
              "size":{
                "width":1226,
                "height":591},
              "linePattern":"none"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b3e89a31a0f041cbbc6ef6f867f6e9ca",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":140,
                    "y":76},
                  "size":{
                    "width":1226,
                    "height":591},
                  "linePattern":"none"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/酒店/u3.png"}}]}}},
  "objectPaths":{
    "63dd5c6754a744d186f783036e6bc07d":{
      "scriptId":"u0",
      "5024326008c74a3f90f4004ca3eb09ad":{
        "scriptId":"u1"},
      "3533708ddaf64d53ab22ac58fbcf7457":{
        "scriptId":"u2"},
      "b3d7ad7f6d44402fbfdfac4c0f1e8cb0":{
        "scriptId":"u3"},
      "b3e89a31a0f041cbbc6ef6f867f6e9ca":{
        "scriptId":"u4"}},
    "9fbd82dc4fc3434783ae7224ba6f6079":{
      "scriptId":"u5"},
    "d3f2de8aa3e541e6a5df15b00e44f221":{
      "scriptId":"u6"},
    "5dc9f5bf1b4e4153bf5daeb426193b09":{
      "scriptId":"u7"},
    "0f34af4bf3a742da8a0655777ed30254":{
      "scriptId":"u8"},
    "adaab992049047c9a290cd3450ec493e":{
      "scriptId":"u9"},
    "e6ed3ec0b094468e923bca41215e0c7b":{
      "scriptId":"u10"},
    "ffd6f994c68e4f2d98ebbb94703662e9":{
      "scriptId":"u11"},
    "a67a0ee2571646988e965983981abc68":{
      "scriptId":"u12"},
    "2a098fbf6a59436f857480e1e2ca1e7b":{
      "scriptId":"u13"},
    "7a0375a7508846f594f9291e36a9cd94":{
      "scriptId":"u14"}}});