$axure.loadCurrentPage({
  "url":"__wifi.html",
  "generationDate":new Date(1419937539886.72),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"719cf72aad4646818d93ca8a6d4125d9",
    "type":"Axure:Page",
    "name":"移动WIFI",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"45de4b930b144665ac5449ea367c75a5",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"c0a6f8e65f9843a4bd1f1d0f4546bc5c"},
{
          "id":"c2ab2958c735434191a28d79b4f98a1f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":85},
            "size":{
              "width":1189,
              "height":205},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a020c17e2a2c4d298ea345aa68207fa7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":85},
                "size":{
                  "width":1189,
                  "height":205},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/电话卡/u5.png"}},
{
          "id":"4dc24a4114db477699e33843f0270ec8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":333},
            "size":{
              "width":1189,
              "height":172},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"611070ec2ff64294945d79692fdf54b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":333},
                "size":{
                  "width":1189,
                  "height":172},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__wifi/u7.png"}},
{
          "id":"6dc76b4948394a68acee0f1d36cd824b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":505},
            "size":{
              "width":1189,
              "height":135},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74e3b52b51fb4fdb98399c1ec03096c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":505},
                "size":{
                  "width":1189,
                  "height":135},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/电话卡/u9.png"}},
{
          "id":"b7ae384eb9d74e138a26b3e7114e4a68",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":309,
              "y":180},
            "size":{
              "width":70,
              "height":30},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f11b54e011964b4d94282f5c04727e1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":309,
                  "y":180},
                "size":{
                  "width":70,
                  "height":30},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/电话卡/u11.png"}},
{
          "id":"013ab5de1c3e426a9cf4b271af14134d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":152,
              "y":287},
            "size":{
              "width":1186,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5b6c2b80fba4259829ffb2d1d8c5ec7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":152,
                  "y":287},
                "size":{
                  "width":1186,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/票券/u15.png"}},
{
          "id":"c1df32ffc8b84a809e8ad546ef5d24d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":233,
              "y":304},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5bbd84743c44e79987cb9e55cf8882b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":233,
                  "y":304},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f8cd84e0b4a4b75838f1f2d0a197391",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":309,
              "y":299},
            "size":{
              "width":91,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c7f702a94f464260a6c6eda0d0229dcd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":299},
            "size":{
              "width":150,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57102fa1bc934b86887396dd8954e525",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":299},
                "size":{
                  "width":150,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2454278facf643248e34c9ec0070e1e4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":635},
            "size":{
              "width":1190,
              "height":399},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e64369cda2c5463a8816364f81f2b764",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":635},
                "size":{
                  "width":1190,
                  "height":399},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/电话卡/u22.png"}},
{
          "id":"04fa2e3eb5f54b96bb9677ddb4fd266d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":1034},
            "size":{
              "width":1188,
              "height":423},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48a1915836754395b89a156d09b25552",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":1034},
                "size":{
                  "width":1188,
                  "height":423},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/票券/u22.png"}},
{
          "id":"980542065bd84278a2425085abd69018",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":1452},
            "size":{
              "width":1189,
              "height":159}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bb56083577b49dd8b59c4356e9a0fa7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":1452},
                "size":{
                  "width":1189,
                  "height":159}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/票券/u24.png"}}]}},
  "masters":{
    "c0a6f8e65f9843a4bd1f1d0f4546bc5c":{
      "packageId":"c0a6f8e65f9843a4bd1f1d0f4546bc5c",
      "type":"Axure:Master",
      "name":"产品管理",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"5024326008c74a3f90f4004ca3eb09ad",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":1364,
                "height":667}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3533708ddaf64d53ab22ac58fbcf7457",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1364,
                    "height":667}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/酒店/u1.png"}},
{
            "id":"b3d7ad7f6d44402fbfdfac4c0f1e8cb0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":140,
                "y":76},
              "size":{
                "width":1226,
                "height":591},
              "linePattern":"none"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b3e89a31a0f041cbbc6ef6f867f6e9ca",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":140,
                    "y":76},
                  "size":{
                    "width":1226,
                    "height":591},
                  "linePattern":"none"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/酒店/u3.png"}}]}}},
  "objectPaths":{
    "45de4b930b144665ac5449ea367c75a5":{
      "scriptId":"u0",
      "5024326008c74a3f90f4004ca3eb09ad":{
        "scriptId":"u1"},
      "3533708ddaf64d53ab22ac58fbcf7457":{
        "scriptId":"u2"},
      "b3d7ad7f6d44402fbfdfac4c0f1e8cb0":{
        "scriptId":"u3"},
      "b3e89a31a0f041cbbc6ef6f867f6e9ca":{
        "scriptId":"u4"}},
    "c2ab2958c735434191a28d79b4f98a1f":{
      "scriptId":"u5"},
    "a020c17e2a2c4d298ea345aa68207fa7":{
      "scriptId":"u6"},
    "4dc24a4114db477699e33843f0270ec8":{
      "scriptId":"u7"},
    "611070ec2ff64294945d79692fdf54b0":{
      "scriptId":"u8"},
    "6dc76b4948394a68acee0f1d36cd824b":{
      "scriptId":"u9"},
    "74e3b52b51fb4fdb98399c1ec03096c4":{
      "scriptId":"u10"},
    "b7ae384eb9d74e138a26b3e7114e4a68":{
      "scriptId":"u11"},
    "f11b54e011964b4d94282f5c04727e1a":{
      "scriptId":"u12"},
    "013ab5de1c3e426a9cf4b271af14134d":{
      "scriptId":"u13"},
    "c5b6c2b80fba4259829ffb2d1d8c5ec7":{
      "scriptId":"u14"},
    "c1df32ffc8b84a809e8ad546ef5d24d8":{
      "scriptId":"u15"},
    "b5bbd84743c44e79987cb9e55cf8882b":{
      "scriptId":"u16"},
    "5f8cd84e0b4a4b75838f1f2d0a197391":{
      "scriptId":"u17"},
    "c7f702a94f464260a6c6eda0d0229dcd":{
      "scriptId":"u18"},
    "57102fa1bc934b86887396dd8954e525":{
      "scriptId":"u19"},
    "2454278facf643248e34c9ec0070e1e4":{
      "scriptId":"u20"},
    "e64369cda2c5463a8816364f81f2b764":{
      "scriptId":"u21"},
    "04fa2e3eb5f54b96bb9677ddb4fd266d":{
      "scriptId":"u22"},
    "48a1915836754395b89a156d09b25552":{
      "scriptId":"u23"},
    "980542065bd84278a2425085abd69018":{
      "scriptId":"u24"},
    "5bb56083577b49dd8b59c4356e9a0fa7":{
      "scriptId":"u25"}}});