$axure.loadCurrentPage({
  "url":"酒店价格设置（删除）.html",
  "generationDate":new Date(1419937541082.79),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1dbbb284799e4adc979aef923d3d8f56",
    "type":"Axure:Page",
    "name":"酒店价格设置（删除）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"58997d3907fa4264a107ddc0d1b0b028",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":0},
            "size":{
              "width":1357,
              "height":660}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f0519a9f66b4fb29629b9e1267419ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":0},
                "size":{
                  "width":1357,
                  "height":660}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店价格设置（删除）/u0.png"}},
{
          "id":"a178866a848b4caca5624dcee39344ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":235,
              "y":250},
            "size":{
              "width":198,
              "height":39},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a522d18d7a04bc5af7b9a31fd4be08e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":235,
                  "y":250},
                "size":{
                  "width":198,
                  "height":39},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店价格设置（删除）/u2.png"}},
{
          "id":"da4caac35ca6426f923b24c0628bd81a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":186,
              "y":330},
            "size":{
              "width":1160,
              "height":330},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f124e420b678439bbe4ff542b4d4652c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":186,
                  "y":330},
                "size":{
                  "width":1160,
                  "height":330},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店价格设置（删除）/u4.png"}},
{
          "id":"b57dbcd1af884d59bad013782b052cfe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":189,
              "y":330},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad4a9a4ef2374f9593b04b79d6d0d48c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":189,
                  "y":330},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46986d9da799483f991dd2550b3eed82",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":328},
            "size":{
              "width":292,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5c7e7e7820c1483f8160c982e1ae14e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":189,
              "y":368},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51b7ed40967d4981a343cbe7dc03ed57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":189,
                  "y":368},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"597ac445fbc7410dae636d75df80bc69",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":366},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9f4fc4ba647c4df1a79329f82080431c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":189,
              "y":403},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5424b31eb1a14c0abe276a969563eab7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":189,
                  "y":403},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05014408d7ef45d8b366b0eff41c5ffa",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":401},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0027c1383e474971aa0bd74f547d9ff4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":189,
              "y":441},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3faf7e4c3a9d490cb1beaf80be95e5cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":189,
                  "y":441},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e95af6a82ce24e63a28c38bc07e565c0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":439},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"42f249d35cb7413c8bae688daef0e8ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":444,
              "y":439},
            "size":{
              "width":20,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a144333ec9b440818d70291c53ce4210",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":444,
                  "y":439},
                "size":{
                  "width":20,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d530c19605c4a99b744d9f233f64642",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":474,
              "y":441},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c37b7833a2424768bd45036a6b5be59c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":189,
              "y":476},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc34ae009c2f40f88fde126e5b17d45b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":189,
                  "y":476},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c65ae9ad60994b109221f42ff9e5a525",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":474},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ce65ebbebeda456ba1101ab8da1d7e00",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":522},
            "size":{
              "width":1130,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/酒店地面价格设置/u26_line.png"}},
{
          "id":"d0ad894e945641ecbaf56e5dc8b00506",
          "label":"酒店套餐ID",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":189,
              "y":544},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d09509ffc59741af94ac303201aa3fc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":189,
                  "y":544},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da98f99470424ba7aca03984ebe616b8",
          "label":"txt酒店套餐ID",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":542},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a56668b263214d80a7dfa8dedb1e358c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":509},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2257d1ea4dba49259b8fc459b733daab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":193,
                  "y":509},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d3f493d4e464bd39aadb5f7b1e646f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":189,
              "y":579},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e45b01a34274d4d95b79c5bf7dc1d59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":189,
                  "y":579},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77fb5bac47f04b378ffed14af919e591",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":577},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"fda1ee72df1c4dd9a8531a5715cfc026",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":189,
              "y":656},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73676d42a43a458caea50e7acd1e8874",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":189,
                  "y":656},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6de34401d7d74dedb8bb234194460cfc",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":654},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ee2ac2c7534840859601e0173a8eb6a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":189,
              "y":691},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48be17c5e3264a6dbf114a78d2f1e67c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":189,
                  "y":691},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"454d6e0b972c4deea3e67a16d0753358",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":689},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1cc1d8cd56594aecbaaed65051655e8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":189,
              "y":726},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a7d76249d464ef9b27409ade81cf9dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":189,
                  "y":726},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6298a24ad8f42b29ec56855c1b8e636",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":724},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"07adfdbc00ea41c39178f652380fbb5c",
          "label":"酒店套餐份数",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":446,
              "y":546},
            "size":{
              "width":57,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60299efaad1d43458270b9277cf4dfcd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":446,
                  "y":546},
                "size":{
                  "width":57,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ebf9bc4333d4a51856fddc1181e126c",
          "label":"txt酒店套餐份数",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":503,
              "y":543},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"408e52c3e4c0478584a132d7bb7ec48a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":556,
              "y":567},
            "size":{
              "width":40,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91ddbad6f3fc4df882ea6ab472f94781",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":556,
                  "y":567},
                "size":{
                  "width":40,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 交通套餐+,<br>交通套餐ID,<br>txt交通套餐ID,<br>交通套餐份数,<br>txt交通套餐份数",
                      "objectsToFades":[{
                          "objectPath":["8416cdc578034610a636973b28e0a478"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["daca81a9556c4443a95c5868c179909a"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["3445733d96ea4c7286378b7c9bde6c8b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["d3d88466f2b74661bc05ebb9cdcdfd35"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["c4e92cd52a4f4aad99cd9a01ad81992a"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/酒店地面价格设置/u47.png"}},
{
          "id":"c98fa8e857d74709b269b9302e9c668a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":446,
              "y":575},
            "size":{
              "width":57,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c3945ebd0a149e7a3e568e2f14c7e6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":446,
                  "y":575},
                "size":{
                  "width":57,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4caf651f32f4fc5908de1b1745b9f6c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":504,
              "y":573},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d51e394c0b4d4a5597d960a0b98e9c8d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":556,
              "y":647},
            "size":{
              "width":40,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"042746cc74e44517881baae2bc717a29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":556,
                  "y":647},
                "size":{
                  "width":40,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/酒店地面价格设置/u47.png"}},
{
          "id":"23879fcef0e74760a1ce807076c2ca1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":446,
              "y":655},
            "size":{
              "width":57,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df6634ddb25b4fc7989e27055f8975ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":446,
                  "y":655},
                "size":{
                  "width":57,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26d8ea3c749f486389b235da74987ff3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":504,
              "y":653},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3293c936ecd04b46bd6c8217d256e3f8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":557,
              "y":681},
            "size":{
              "width":40,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"015e4bed23234a15904b2337a444617b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":557,
                  "y":681},
                "size":{
                  "width":40,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/酒店地面价格设置/u47.png"}},
{
          "id":"9da7d17b815943e1b1241a5c0a90008f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":447,
              "y":689},
            "size":{
              "width":57,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c266244eb5eb4c539df15f4ee719812c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":447,
                  "y":689},
                "size":{
                  "width":57,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"abd0061444a64c528226f99f573aa3fd",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":505,
              "y":687},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8bc19206e5ac41b7b9a16b30a5640394",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":557,
              "y":719},
            "size":{
              "width":40,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ccad0c2d13a42c4ac282a2ad4606eff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":557,
                  "y":719},
                "size":{
                  "width":40,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/酒店地面价格设置/u47.png"}},
{
          "id":"bba6383cebd249c594d314c8370705f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":447,
              "y":727},
            "size":{
              "width":57,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"339b56a5ce5d4a79bc8d3b7a0fc44b70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":447,
                  "y":727},
                "size":{
                  "width":57,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2a4a67d891643a2b0ad4a7ac48ec0cf",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":505,
              "y":725},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"daca81a9556c4443a95c5868c179909a",
          "label":"交通套餐ID",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":189,
              "y":617},
            "size":{
              "width":94,
              "height":26},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7743e0725033448da8c9e5f0cddb3540",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":189,
                  "y":617},
                "size":{
                  "width":94,
                  "height":26},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3445733d96ea4c7286378b7c9bde6c8b",
          "label":"txt交通套餐ID",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "location":{
              "x":309,
              "y":615},
            "size":{
              "width":127,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"8416cdc578034610a636973b28e0a478",
          "label":"交通套餐+",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":556,
              "y":605},
            "size":{
              "width":40,
              "height":35},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4513ab6064944a0194cad036e3139060",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":556,
                  "y":605},
                "size":{
                  "width":40,
                  "height":35},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/酒店地面价格设置/u47.png"}},
{
          "id":"d3d88466f2b74661bc05ebb9cdcdfd35",
          "label":"交通套餐份数",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":446,
              "y":613},
            "size":{
              "width":57,
              "height":26},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23a1283130ee4a7f90a46695b756b8b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":446,
                  "y":613},
                "size":{
                  "width":57,
                  "height":26},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4e92cd52a4f4aad99cd9a01ad81992a",
          "label":"txt交通套餐份数",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "location":{
              "x":504,
              "y":611},
            "size":{
              "width":40,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"0b0c4e1448734ec6bdccf7acf8d319bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":621,
              "y":543},
            "size":{
              "width":310,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ef80457eac74d70aac4b186e12c2a0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":621,
                  "y":543},
                "size":{
                  "width":310,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5851d04aaff4cc9a774d26a8a93f181",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":203,
              "y":762},
            "size":{
              "width":160,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36d550e459764dc79e6e9eae5d4f478d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":203,
                  "y":762},
                "size":{
                  "width":160,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20c5f3236697493cb6f42076172b8e25",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":354,
              "y":762},
            "size":{
              "width":30,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9a8a882de4c4a0ab8e8277b35a3234d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":354,
                  "y":762},
                "size":{
                  "width":30,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c92c22fd6d244e02ba34ac803aed3fb0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":404,
              "y":762},
            "size":{
              "width":439,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bc7741afd4540538be6f381944c7755",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":404,
                  "y":762},
                "size":{
                  "width":439,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b30e48795a0b499e81936c399c60c75b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":623,
              "y":575},
            "size":{
              "width":300,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac5978515684492b81041bdeef58f4d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":623,
                  "y":575},
                "size":{
                  "width":300,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e8916392426044f38ebc7b18b572006f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":193,
              "y":796},
            "size":{
              "width":540,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"807bc4f1282a44d784bd364b0b3c943a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":193,
                  "y":796},
                "size":{
                  "width":540,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd0c98924e524e52bbd5ed6cbee8422d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":453,
              "y":478},
            "size":{
              "width":647,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dac9f3859cbc469fb4d3f4a03063ebe2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":453,
                  "y":478},
                "size":{
                  "width":647,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "58997d3907fa4264a107ddc0d1b0b028":{
      "scriptId":"u0"},
    "4f0519a9f66b4fb29629b9e1267419ab":{
      "scriptId":"u1"},
    "a178866a848b4caca5624dcee39344ad":{
      "scriptId":"u2"},
    "7a522d18d7a04bc5af7b9a31fd4be08e":{
      "scriptId":"u3"},
    "da4caac35ca6426f923b24c0628bd81a":{
      "scriptId":"u4"},
    "f124e420b678439bbe4ff542b4d4652c":{
      "scriptId":"u5"},
    "b57dbcd1af884d59bad013782b052cfe":{
      "scriptId":"u6"},
    "ad4a9a4ef2374f9593b04b79d6d0d48c":{
      "scriptId":"u7"},
    "46986d9da799483f991dd2550b3eed82":{
      "scriptId":"u8"},
    "5c7e7e7820c1483f8160c982e1ae14e4":{
      "scriptId":"u9"},
    "51b7ed40967d4981a343cbe7dc03ed57":{
      "scriptId":"u10"},
    "597ac445fbc7410dae636d75df80bc69":{
      "scriptId":"u11"},
    "9f4fc4ba647c4df1a79329f82080431c":{
      "scriptId":"u12"},
    "5424b31eb1a14c0abe276a969563eab7":{
      "scriptId":"u13"},
    "05014408d7ef45d8b366b0eff41c5ffa":{
      "scriptId":"u14"},
    "0027c1383e474971aa0bd74f547d9ff4":{
      "scriptId":"u15"},
    "3faf7e4c3a9d490cb1beaf80be95e5cc":{
      "scriptId":"u16"},
    "e95af6a82ce24e63a28c38bc07e565c0":{
      "scriptId":"u17"},
    "42f249d35cb7413c8bae688daef0e8ef":{
      "scriptId":"u18"},
    "a144333ec9b440818d70291c53ce4210":{
      "scriptId":"u19"},
    "3d530c19605c4a99b744d9f233f64642":{
      "scriptId":"u20"},
    "c37b7833a2424768bd45036a6b5be59c":{
      "scriptId":"u21"},
    "bc34ae009c2f40f88fde126e5b17d45b":{
      "scriptId":"u22"},
    "c65ae9ad60994b109221f42ff9e5a525":{
      "scriptId":"u23"},
    "ce65ebbebeda456ba1101ab8da1d7e00":{
      "scriptId":"u24"},
    "d0ad894e945641ecbaf56e5dc8b00506":{
      "scriptId":"u25"},
    "d09509ffc59741af94ac303201aa3fc9":{
      "scriptId":"u26"},
    "da98f99470424ba7aca03984ebe616b8":{
      "scriptId":"u27"},
    "a56668b263214d80a7dfa8dedb1e358c":{
      "scriptId":"u28"},
    "2257d1ea4dba49259b8fc459b733daab":{
      "scriptId":"u29"},
    "1d3f493d4e464bd39aadb5f7b1e646f0":{
      "scriptId":"u30"},
    "1e45b01a34274d4d95b79c5bf7dc1d59":{
      "scriptId":"u31"},
    "77fb5bac47f04b378ffed14af919e591":{
      "scriptId":"u32"},
    "fda1ee72df1c4dd9a8531a5715cfc026":{
      "scriptId":"u33"},
    "73676d42a43a458caea50e7acd1e8874":{
      "scriptId":"u34"},
    "6de34401d7d74dedb8bb234194460cfc":{
      "scriptId":"u35"},
    "ee2ac2c7534840859601e0173a8eb6a9":{
      "scriptId":"u36"},
    "48be17c5e3264a6dbf114a78d2f1e67c":{
      "scriptId":"u37"},
    "454d6e0b972c4deea3e67a16d0753358":{
      "scriptId":"u38"},
    "1cc1d8cd56594aecbaaed65051655e8d":{
      "scriptId":"u39"},
    "8a7d76249d464ef9b27409ade81cf9dd":{
      "scriptId":"u40"},
    "a6298a24ad8f42b29ec56855c1b8e636":{
      "scriptId":"u41"},
    "07adfdbc00ea41c39178f652380fbb5c":{
      "scriptId":"u42"},
    "60299efaad1d43458270b9277cf4dfcd":{
      "scriptId":"u43"},
    "6ebf9bc4333d4a51856fddc1181e126c":{
      "scriptId":"u44"},
    "408e52c3e4c0478584a132d7bb7ec48a":{
      "scriptId":"u45"},
    "91ddbad6f3fc4df882ea6ab472f94781":{
      "scriptId":"u46"},
    "c98fa8e857d74709b269b9302e9c668a":{
      "scriptId":"u47"},
    "2c3945ebd0a149e7a3e568e2f14c7e6e":{
      "scriptId":"u48"},
    "c4caf651f32f4fc5908de1b1745b9f6c":{
      "scriptId":"u49"},
    "d51e394c0b4d4a5597d960a0b98e9c8d":{
      "scriptId":"u50"},
    "042746cc74e44517881baae2bc717a29":{
      "scriptId":"u51"},
    "23879fcef0e74760a1ce807076c2ca1a":{
      "scriptId":"u52"},
    "df6634ddb25b4fc7989e27055f8975ad":{
      "scriptId":"u53"},
    "26d8ea3c749f486389b235da74987ff3":{
      "scriptId":"u54"},
    "3293c936ecd04b46bd6c8217d256e3f8":{
      "scriptId":"u55"},
    "015e4bed23234a15904b2337a444617b":{
      "scriptId":"u56"},
    "9da7d17b815943e1b1241a5c0a90008f":{
      "scriptId":"u57"},
    "c266244eb5eb4c539df15f4ee719812c":{
      "scriptId":"u58"},
    "abd0061444a64c528226f99f573aa3fd":{
      "scriptId":"u59"},
    "8bc19206e5ac41b7b9a16b30a5640394":{
      "scriptId":"u60"},
    "0ccad0c2d13a42c4ac282a2ad4606eff":{
      "scriptId":"u61"},
    "bba6383cebd249c594d314c8370705f9":{
      "scriptId":"u62"},
    "339b56a5ce5d4a79bc8d3b7a0fc44b70":{
      "scriptId":"u63"},
    "f2a4a67d891643a2b0ad4a7ac48ec0cf":{
      "scriptId":"u64"},
    "daca81a9556c4443a95c5868c179909a":{
      "scriptId":"u65"},
    "7743e0725033448da8c9e5f0cddb3540":{
      "scriptId":"u66"},
    "3445733d96ea4c7286378b7c9bde6c8b":{
      "scriptId":"u67"},
    "8416cdc578034610a636973b28e0a478":{
      "scriptId":"u68"},
    "4513ab6064944a0194cad036e3139060":{
      "scriptId":"u69"},
    "d3d88466f2b74661bc05ebb9cdcdfd35":{
      "scriptId":"u70"},
    "23a1283130ee4a7f90a46695b756b8b2":{
      "scriptId":"u71"},
    "c4e92cd52a4f4aad99cd9a01ad81992a":{
      "scriptId":"u72"},
    "0b0c4e1448734ec6bdccf7acf8d319bc":{
      "scriptId":"u73"},
    "2ef80457eac74d70aac4b186e12c2a0a":{
      "scriptId":"u74"},
    "f5851d04aaff4cc9a774d26a8a93f181":{
      "scriptId":"u75"},
    "36d550e459764dc79e6e9eae5d4f478d":{
      "scriptId":"u76"},
    "20c5f3236697493cb6f42076172b8e25":{
      "scriptId":"u77"},
    "c9a8a882de4c4a0ab8e8277b35a3234d":{
      "scriptId":"u78"},
    "c92c22fd6d244e02ba34ac803aed3fb0":{
      "scriptId":"u79"},
    "7bc7741afd4540538be6f381944c7755":{
      "scriptId":"u80"},
    "b30e48795a0b499e81936c399c60c75b":{
      "scriptId":"u81"},
    "ac5978515684492b81041bdeef58f4d5":{
      "scriptId":"u82"},
    "e8916392426044f38ebc7b18b572006f":{
      "scriptId":"u83"},
    "807bc4f1282a44d784bd364b0b3c943a":{
      "scriptId":"u84"},
    "dd0c98924e524e52bbd5ed6cbee8422d":{
      "scriptId":"u85"},
    "dac9f3859cbc469fb4d3f4a03063ebe2":{
      "scriptId":"u86"}}});