$axure.loadCurrentPage({
  "url":"预订限制.html",
  "generationDate":new Date(1419937541334.8),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"65017522153f41d98bb0fa93bf608c61",
    "type":"Axure:Page",
    "name":"预订限制",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e3c9dce1230b4a658b538177723bde0f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1364,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"746727616f494411bba0e7d8ebedc8af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1364,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店/u1.png"}},
{
          "id":"d885fb7a507e4ca69f014822a2697fb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":76},
            "size":{
              "width":1226,
              "height":591},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ed424f29b4745a39d0e166b07b7f483",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":76},
                "size":{
                  "width":1226,
                  "height":591},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店/u3.png"}},
{
          "id":"7242d4536fba4e12988ab5167cddc392",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":88},
            "size":{
              "width":1157,
              "height":319},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcbc433e5aa04fefae7004bd599adaac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":88},
                "size":{
                  "width":1157,
                  "height":319},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预订限制/u4.png"}},
{
          "id":"ece88c319cf649208b998e1cf1d1d514",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":445},
            "size":{
              "width":1157,
              "height":171},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0421da694124f74962a6a734bdb5f95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":445},
                "size":{
                  "width":1157,
                  "height":171},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预订限制/u6.png"}},
{
          "id":"9b5f905dd52b492fa045b1ce5ed18e80",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":220},
            "size":{
              "width":530,
              "height":180},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00ec586b4d3349ca8a460e754f49c904",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":220},
                "size":{
                  "width":530,
                  "height":180},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预订限制/u8.png"}},
{
          "id":"c2e326bc4351450ba44bec75872c5bc1",
          "label":"imgPassenger",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":224},
            "size":{
              "width":516,
              "height":178}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78d6efe028744dd482229203107d6ae3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":379,
                  "y":224},
                "size":{
                  "width":516,
                  "height":178}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预订限制/imgpassenger_u10.png"}},
{
          "id":"c49b7ed7f31947cd8bd013adef55f100",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":310,
              "y":304},
            "size":{
              "width":28,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c05f1f08d7549a298d616f2cf295812",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":310,
                  "y":304},
                "size":{
                  "width":28,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onCheckedChange":{
              "description":"OnCheckedChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 imgPassenger,<br>imgPassenger1",
                      "objectsToFades":[{
                          "objectPath":["c2e326bc4351450ba44bec75872c5bc1"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["1c80afe54da04df0a6e788e349e3a82e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}}},
{
          "id":"3090abf1e6334a4bb082d9539b8193da",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":343,
              "y":304},
            "size":{
              "width":28,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccac52bb3f0941dd931264e7db47e4ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":343,
                  "y":304},
                "size":{
                  "width":28,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onCheckedChange":{
              "description":"OnCheckedChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 imgPassenger,<br>imgPassenger1",
                      "objectsToFades":[{
                          "objectPath":["c2e326bc4351450ba44bec75872c5bc1"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["1c80afe54da04df0a6e788e349e3a82e"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}}},
{
          "id":"b5217899fba94a78a6f69664b63ba6d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":312,
              "y":467},
            "size":{
              "width":60,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b00fc3ebf1b45d9af999e76cf6ccfee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":312,
                  "y":467},
                "size":{
                  "width":60,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预订限制/u16.png"}},
{
          "id":"4e378d865cc2431e87b19de604dc9def",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":311,
              "y":476},
            "size":{
              "width":28,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2555f10763f8479f88b11c32ade22c98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":311,
                  "y":476},
                "size":{
                  "width":28,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onCheckedChange":{
              "description":"OnCheckedChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (复选框),<br>(复选框),<br>(复选框)",
                      "objectsToFades":[{
                          "objectPath":["5e02da1ac57d459598d05286749ba1d0"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["cb53e1e9679f4231aae6d4bc8884cebe"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["646eec79bc994533931d4ffe1796405d"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}}},
{
          "id":"390d8a1dd6a8420bacb3e1dc54b0c58f",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":344,
              "y":476},
            "size":{
              "width":28,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03fdbfcfcd46422a9dcbb6a9361a9e8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":344,
                  "y":476},
                "size":{
                  "width":28,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onCheckedChange":{
              "description":"OnCheckedChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 (复选框),<br>(复选框),<br>(复选框)",
                      "objectsToFades":[{
                          "objectPath":["5e02da1ac57d459598d05286749ba1d0"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["cb53e1e9679f4231aae6d4bc8884cebe"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["646eec79bc994533931d4ffe1796405d"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}}},
{
          "id":"1c80afe54da04df0a6e788e349e3a82e",
          "label":"imgPassenger1",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":377,
              "y":404},
            "size":{
              "width":225,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe5033b0e98e469eab265ebbddc5a54e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":377,
                  "y":404},
                "size":{
                  "width":225,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预订限制/imgpassenger1_u22.png"}},
{
          "id":"d736d8b33f3e485f81f0c4f585fcc3fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":385,
              "y":489},
            "size":{
              "width":200,
              "height":21},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"385c63423a784940b89ca65919f76e59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":385,
                  "y":489},
                "size":{
                  "width":200,
                  "height":21},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预订限制/u24.png"}},
{
          "id":"8b252090def648e2896d289782cabf08",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":382,
              "y":460},
            "size":{
              "width":908,
              "height":50},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a583c6df0e5642e493035bef121d069d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":382,
                  "y":460},
                "size":{
                  "width":908,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预订限制/u26.png"}},
{
          "id":"2fa80e4176fd4674b2b7c1df22556acb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":667},
            "size":{
              "width":710,
              "height":263}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bd7f615fc8246a09ca3e411bddd6987",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":667},
                "size":{
                  "width":710,
                  "height":263}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e02da1ac57d459598d05286749ba1d0",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":385,
              "y":476},
            "size":{
              "width":155,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31c91190ac144102a0bc1484caaeb15f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":385,
                  "y":476},
                "size":{
                  "width":155,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"cb53e1e9679f4231aae6d4bc8884cebe",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":476},
            "size":{
              "width":155,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d6d8c4fe15a49409098588bfb722eae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":476},
                "size":{
                  "width":155,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"646eec79bc994533931d4ffe1796405d",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":715,
              "y":476},
            "size":{
              "width":180,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33665c00f4834c43befdeb5d618432c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":715,
                  "y":476},
                "size":{
                  "width":180,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"4183df4ab3ae4934b7e565bc006b7bc5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":209,
              "y":616},
            "size":{
              "width":1157,
              "height":171},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c65418d608f4d36b7e8cee32edbf53f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":209,
                  "y":616},
                "size":{
                  "width":1157,
                  "height":171},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预订限制/u6.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "e3c9dce1230b4a658b538177723bde0f":{
      "scriptId":"u0"},
    "746727616f494411bba0e7d8ebedc8af":{
      "scriptId":"u1"},
    "d885fb7a507e4ca69f014822a2697fb7":{
      "scriptId":"u2"},
    "2ed424f29b4745a39d0e166b07b7f483":{
      "scriptId":"u3"},
    "7242d4536fba4e12988ab5167cddc392":{
      "scriptId":"u4"},
    "fcbc433e5aa04fefae7004bd599adaac":{
      "scriptId":"u5"},
    "ece88c319cf649208b998e1cf1d1d514":{
      "scriptId":"u6"},
    "a0421da694124f74962a6a734bdb5f95":{
      "scriptId":"u7"},
    "9b5f905dd52b492fa045b1ce5ed18e80":{
      "scriptId":"u8"},
    "00ec586b4d3349ca8a460e754f49c904":{
      "scriptId":"u9"},
    "c2e326bc4351450ba44bec75872c5bc1":{
      "scriptId":"u10"},
    "78d6efe028744dd482229203107d6ae3":{
      "scriptId":"u11"},
    "c49b7ed7f31947cd8bd013adef55f100":{
      "scriptId":"u12"},
    "1c05f1f08d7549a298d616f2cf295812":{
      "scriptId":"u13"},
    "3090abf1e6334a4bb082d9539b8193da":{
      "scriptId":"u14"},
    "ccac52bb3f0941dd931264e7db47e4ca":{
      "scriptId":"u15"},
    "b5217899fba94a78a6f69664b63ba6d9":{
      "scriptId":"u16"},
    "8b00fc3ebf1b45d9af999e76cf6ccfee":{
      "scriptId":"u17"},
    "4e378d865cc2431e87b19de604dc9def":{
      "scriptId":"u18"},
    "2555f10763f8479f88b11c32ade22c98":{
      "scriptId":"u19"},
    "390d8a1dd6a8420bacb3e1dc54b0c58f":{
      "scriptId":"u20"},
    "03fdbfcfcd46422a9dcbb6a9361a9e8f":{
      "scriptId":"u21"},
    "1c80afe54da04df0a6e788e349e3a82e":{
      "scriptId":"u22"},
    "fe5033b0e98e469eab265ebbddc5a54e":{
      "scriptId":"u23"},
    "d736d8b33f3e485f81f0c4f585fcc3fd":{
      "scriptId":"u24"},
    "385c63423a784940b89ca65919f76e59":{
      "scriptId":"u25"},
    "8b252090def648e2896d289782cabf08":{
      "scriptId":"u26"},
    "a583c6df0e5642e493035bef121d069d":{
      "scriptId":"u27"},
    "2fa80e4176fd4674b2b7c1df22556acb":{
      "scriptId":"u28"},
    "7bd7f615fc8246a09ca3e411bddd6987":{
      "scriptId":"u29"},
    "5e02da1ac57d459598d05286749ba1d0":{
      "scriptId":"u30"},
    "31c91190ac144102a0bc1484caaeb15f":{
      "scriptId":"u31"},
    "cb53e1e9679f4231aae6d4bc8884cebe":{
      "scriptId":"u32"},
    "1d6d8c4fe15a49409098588bfb722eae":{
      "scriptId":"u33"},
    "646eec79bc994533931d4ffe1796405d":{
      "scriptId":"u34"},
    "33665c00f4834c43befdeb5d618432c8":{
      "scriptId":"u35"},
    "4183df4ab3ae4934b7e565bc006b7bc5":{
      "scriptId":"u36"},
    "3c65418d608f4d36b7e8cee32edbf53f":{
      "scriptId":"u37"}}});