$axure.loadCurrentPage({
  "url":"订单查询_1.html",
  "generationDate":new Date(1419937542980.89),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"fa5c987e90dc4051932ab3250dee6b86",
    "type":"Axure:Page",
    "name":"订单查询",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6ced2b3236b247a2a233bfccb44761e1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "size":{
              "width":1323,
              "height":575}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14c887b2e26b458db6b285b638827e8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "size":{
                  "width":1323,
                  "height":575}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单查询_1/u0.png"}},
{
          "id":"dd3afc10b98044d58bc9b87d2138d139",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":1206,
              "y":293},
            "size":{
              "width":50,
              "height":30},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19cb926b696b4bcb9ef454fd9f6e3762",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":1206,
                  "y":293},
                "size":{
                  "width":50,
                  "height":30},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 订单详情",
                      "target":{
                        "targetType":"page",
                        "url":"订单详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/订单查询_1/u2.png"}},
{
          "id":"73fb0c9fdbce4f4aa794695dcbe18c3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":1206,
              "y":350},
            "size":{
              "width":50,
              "height":30},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fab22278f1447819f706e09c4e70ec6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":1206,
                  "y":350},
                "size":{
                  "width":50,
                  "height":30},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 订单详情",
                      "target":{
                        "targetType":"page",
                        "url":"订单详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/订单查询_1/u2.png"}},
{
          "id":"1f9e926eca874bedaf0d812223a01281",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":1206,
              "y":408},
            "size":{
              "width":50,
              "height":30},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7df385babbc7451990b49edf6cf917bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":1206,
                  "y":408},
                "size":{
                  "width":50,
                  "height":30},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 订单详情",
                      "target":{
                        "targetType":"page",
                        "url":"订单详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/订单查询_1/u2.png"}},
{
          "id":"da4aca0b75d54d75af2a6c4873a7bf6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":1206,
              "y":465},
            "size":{
              "width":50,
              "height":30},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abfb4dd41bb347a78a847d7df7c529f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":1206,
                  "y":465},
                "size":{
                  "width":50,
                  "height":30},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 订单详情",
                      "target":{
                        "targetType":"page",
                        "url":"订单详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/订单查询_1/u2.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "6ced2b3236b247a2a233bfccb44761e1":{
      "scriptId":"u0"},
    "14c887b2e26b458db6b285b638827e8e":{
      "scriptId":"u1"},
    "dd3afc10b98044d58bc9b87d2138d139":{
      "scriptId":"u2"},
    "19cb926b696b4bcb9ef454fd9f6e3762":{
      "scriptId":"u3"},
    "73fb0c9fdbce4f4aa794695dcbe18c3b":{
      "scriptId":"u4"},
    "2fab22278f1447819f706e09c4e70ec6":{
      "scriptId":"u5"},
    "1f9e926eca874bedaf0d812223a01281":{
      "scriptId":"u6"},
    "7df385babbc7451990b49edf6cf917bd":{
      "scriptId":"u7"},
    "da4aca0b75d54d75af2a6c4873a7bf6e":{
      "scriptId":"u8"},
    "abfb4dd41bb347a78a847d7df7c529f2":{
      "scriptId":"u9"}}});