$axure.loadCurrentPage({
  "url":"操作日志.html",
  "generationDate":new Date(1419937542733.88),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a3efcf08d7704f7eb37c62791080a11a",
    "type":"Axure:Page",
    "name":"操作日志",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"815e077b3e2f4d3c86f4e2256d777a06",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":127,
              "y":10},
            "size":{
              "width":753,
              "height":350}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7daa77b8b6c249e28068a704aa0732de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":127,
                  "y":10},
                "size":{
                  "width":753,
                  "height":350}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/操作日志/u0.png"}},
{
          "id":"c2c8a152f5074b0b9cce6164cc0e43ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF458CC9},
            "location":{
              "x":127,
              "y":10},
            "size":{
              "width":753,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a5d0a47f09d4824bd761b146fd21b07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF458CC9},
                "location":{
                  "x":127,
                  "y":10},
                "size":{
                  "width":753,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/操作日志/u2.png"}},
{
          "id":"7974741f9d704fb181a1ddd7092a9055",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":846,
              "y":20},
            "size":{
              "width":30,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e37f37902fad4ea0bb7cccd8d2a267d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":846,
                  "y":20},
                "size":{
                  "width":30,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发送邮件/u4.png"}},
{
          "id":"79d54d5a61344a298e51f9e46e2152ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":140,
              "y":22},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c44d90b6dc54b038c0c8240502220fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":22},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ddde26492e94ae386d6f0abe8444580",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEAF0F7},
            "location":{
              "x":140,
              "y":60},
            "size":{
              "width":730,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD5DFE8}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba1da04dd888499bb3df625d4cae10a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEAF0F7},
                "location":{
                  "x":140,
                  "y":60},
                "size":{
                  "width":730,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD5DFE8}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/操作日志/u8.png"}},
{
          "id":"0389e35adfc14637b22284222c576407",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5252F2,
              "opacity":1},
            "location":{
              "x":183,
              "y":77},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e42f0d960404382813076ca8c3e4368",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF5252F2,
                  "opacity":1},
                "location":{
                  "x":183,
                  "y":77},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5bc148938c6a42b0b610b014c7d224a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5252F2,
              "opacity":1},
            "location":{
              "x":295,
              "y":76},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"757e09e5b58147098b699e018aae07a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF5252F2,
                  "opacity":1},
                "location":{
                  "x":295,
                  "y":76},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"def255111502473eaa2b0e226ffaa1d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5252F2,
              "opacity":1},
            "location":{
              "x":416,
              "y":76},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cb25127ad274869ab12ce1a7536224c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF5252F2,
                  "opacity":1},
                "location":{
                  "x":416,
                  "y":76},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5def870227054704b66e123d0766534f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5252F2,
              "opacity":1},
            "location":{
              "x":747,
              "y":76},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a200d0dbc1da4d6284950222cfc55ae8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF5252F2,
                  "opacity":1},
                "location":{
                  "x":747,
                  "y":76},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6f21273365040d6ac77f09172e47145",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":109},
            "size":{
              "width":730,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD5DFE8}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6272ec2810c47ac82a7bad91eabdab3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":109},
                "size":{
                  "width":730,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD5DFE8}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/操作日志/u18.png"}},
{
          "id":"ba95cfa533ca48fbbfd67785eb167be7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":292,
              "y":121},
            "size":{
              "width":73,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a352c5ba9e4d463b8abe7c60ba683ccc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":292,
                  "y":121},
                "size":{
                  "width":73,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f94a83b40394ae49cab0ae02ce682b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":414,
              "y":121},
            "size":{
              "width":226,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d9d16a73d144732b47e861fabda4f7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":414,
                  "y":121},
                "size":{
                  "width":226,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24a84f35db4b4a7daa892ddaf14993cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":741,
              "y":122},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fa72e1ba2e94ba1bff54d48fe849f8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":741,
                  "y":122},
                "size":{
                  "width":60,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95544da9d6e14471a91d8ce4bf39b85b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":158},
            "size":{
              "width":730,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD5DFE8}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c18f84d3478a4926820ba03caf010d30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":158},
                "size":{
                  "width":730,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD5DFE8}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/操作日志/u18.png"}},
{
          "id":"9d8bc17cb72840e8a9758eea8b4a363d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":292,
              "y":171},
            "size":{
              "width":73,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e807c250f635429bb74197b1d22cf6bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":292,
                  "y":171},
                "size":{
                  "width":73,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b718f4af41fb47789c8fb0e24519dac0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":414,
              "y":171},
            "size":{
              "width":226,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71de5d35ad794c3389e7d560a7946822",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":414,
                  "y":171},
                "size":{
                  "width":226,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"889d51992c89480dac5fdfe7779df72b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":207},
            "size":{
              "width":730,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD5DFE8}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ed620c2295e4a9cb48a12341503f2ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":207},
                "size":{
                  "width":730,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD5DFE8}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/操作日志/u18.png"}},
{
          "id":"1eea0bed34644b4d925c2017d57c3b51",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":292,
              "y":221},
            "size":{
              "width":73,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7de23c45bb8046e7b591651b8edc8705",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":292,
                  "y":221},
                "size":{
                  "width":73,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7da0d9351d0f4eb1b2149d86216ba17c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":414,
              "y":221},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac76f76275b54fe69b55e9981d6a8171",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":414,
                  "y":221},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d8f947523424a80a914e97f737f17d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":256},
            "size":{
              "width":730,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD5DFE8}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40611c450677490c8f5ab773b76ff81c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":256},
                "size":{
                  "width":730,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD5DFE8}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/操作日志/u18.png"}},
{
          "id":"8e51e3dc3f80478d8480a26c0fbc4c6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":292,
              "y":271},
            "size":{
              "width":73,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d48693069f34c37814a3127b2911e04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":292,
                  "y":271},
                "size":{
                  "width":73,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2718d630066b4eeab808f9fb4b5464ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":414,
              "y":271},
            "size":{
              "width":186,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a661b64ea0b4bcf96e2c77512d0beba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":414,
                  "y":271},
                "size":{
                  "width":186,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"987d21211c1d4bfdab2f10da636264b2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":575,
              "y":314},
            "size":{
              "width":301,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5b724e8c0b843208bf8a5184ea02705",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":575,
                  "y":314},
                "size":{
                  "width":301,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单查询/u143.png"}},
{
          "id":"d84b1604b4e14571ab8e4a89ac068ba8",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":537,
              "y":316},
            "size":{
              "width":40,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"16acd6e95b1b49fcb3e6760616d1a65f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":468,
              "y":318},
            "size":{
              "width":71,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8eaf8901f25240d4b18f914450e0f2d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":468,
                  "y":318},
                "size":{
                  "width":71,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c9566e53e014e1fb3c7a410890bd946",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":167,
              "y":121},
            "size":{
              "width":73,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a78c2962a6004b48ba821d9815c992ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":167,
                  "y":121},
                "size":{
                  "width":73,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a8684c78d2b4d9a9b1eb87bca1aa21e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":167,
              "y":171},
            "size":{
              "width":73,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0b4ce689c25496891e9ed6c83f25eac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":167,
                  "y":171},
                "size":{
                  "width":73,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4cd2f81fd6324a009d2feb78a393afdd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":167,
              "y":221},
            "size":{
              "width":73,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"387a11cfaebc4deea01bf12de6fed64b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":167,
                  "y":221},
                "size":{
                  "width":73,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e816eb20e4c4db78b9db53840ed232c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":167,
              "y":271},
            "size":{
              "width":73,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ef64eebb69c47618df5d36e1d6e41ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":167,
                  "y":271},
                "size":{
                  "width":73,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e2e419e4d1d4643aba75f72c82650e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":741,
              "y":171},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b277a9b5cf5438a89f9ae262aa6cbdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":741,
                  "y":171},
                "size":{
                  "width":60,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aeb36e8826fe43a8ac79af46d10624a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":741,
              "y":222},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31c5c797ae474fa2a40001ea864f746b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":741,
                  "y":222},
                "size":{
                  "width":60,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dc2c08d1360649d89af1504ca03bcf12",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":741,
              "y":272},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e37d87eca364641af466a3dc3662a22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":741,
                  "y":272},
                "size":{
                  "width":60,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "815e077b3e2f4d3c86f4e2256d777a06":{
      "scriptId":"u0"},
    "7daa77b8b6c249e28068a704aa0732de":{
      "scriptId":"u1"},
    "c2c8a152f5074b0b9cce6164cc0e43ee":{
      "scriptId":"u2"},
    "8a5d0a47f09d4824bd761b146fd21b07":{
      "scriptId":"u3"},
    "7974741f9d704fb181a1ddd7092a9055":{
      "scriptId":"u4"},
    "e37f37902fad4ea0bb7cccd8d2a267d7":{
      "scriptId":"u5"},
    "79d54d5a61344a298e51f9e46e2152ef":{
      "scriptId":"u6"},
    "1c44d90b6dc54b038c0c8240502220fe":{
      "scriptId":"u7"},
    "3ddde26492e94ae386d6f0abe8444580":{
      "scriptId":"u8"},
    "ba1da04dd888499bb3df625d4cae10a3":{
      "scriptId":"u9"},
    "0389e35adfc14637b22284222c576407":{
      "scriptId":"u10"},
    "2e42f0d960404382813076ca8c3e4368":{
      "scriptId":"u11"},
    "5bc148938c6a42b0b610b014c7d224a1":{
      "scriptId":"u12"},
    "757e09e5b58147098b699e018aae07a7":{
      "scriptId":"u13"},
    "def255111502473eaa2b0e226ffaa1d5":{
      "scriptId":"u14"},
    "6cb25127ad274869ab12ce1a7536224c":{
      "scriptId":"u15"},
    "5def870227054704b66e123d0766534f":{
      "scriptId":"u16"},
    "a200d0dbc1da4d6284950222cfc55ae8":{
      "scriptId":"u17"},
    "c6f21273365040d6ac77f09172e47145":{
      "scriptId":"u18"},
    "f6272ec2810c47ac82a7bad91eabdab3":{
      "scriptId":"u19"},
    "ba95cfa533ca48fbbfd67785eb167be7":{
      "scriptId":"u20"},
    "a352c5ba9e4d463b8abe7c60ba683ccc":{
      "scriptId":"u21"},
    "7f94a83b40394ae49cab0ae02ce682b5":{
      "scriptId":"u22"},
    "9d9d16a73d144732b47e861fabda4f7f":{
      "scriptId":"u23"},
    "24a84f35db4b4a7daa892ddaf14993cc":{
      "scriptId":"u24"},
    "5fa72e1ba2e94ba1bff54d48fe849f8c":{
      "scriptId":"u25"},
    "95544da9d6e14471a91d8ce4bf39b85b":{
      "scriptId":"u26"},
    "c18f84d3478a4926820ba03caf010d30":{
      "scriptId":"u27"},
    "9d8bc17cb72840e8a9758eea8b4a363d":{
      "scriptId":"u28"},
    "e807c250f635429bb74197b1d22cf6bc":{
      "scriptId":"u29"},
    "b718f4af41fb47789c8fb0e24519dac0":{
      "scriptId":"u30"},
    "71de5d35ad794c3389e7d560a7946822":{
      "scriptId":"u31"},
    "889d51992c89480dac5fdfe7779df72b":{
      "scriptId":"u32"},
    "4ed620c2295e4a9cb48a12341503f2ce":{
      "scriptId":"u33"},
    "1eea0bed34644b4d925c2017d57c3b51":{
      "scriptId":"u34"},
    "7de23c45bb8046e7b591651b8edc8705":{
      "scriptId":"u35"},
    "7da0d9351d0f4eb1b2149d86216ba17c":{
      "scriptId":"u36"},
    "ac76f76275b54fe69b55e9981d6a8171":{
      "scriptId":"u37"},
    "4d8f947523424a80a914e97f737f17d4":{
      "scriptId":"u38"},
    "40611c450677490c8f5ab773b76ff81c":{
      "scriptId":"u39"},
    "8e51e3dc3f80478d8480a26c0fbc4c6e":{
      "scriptId":"u40"},
    "2d48693069f34c37814a3127b2911e04":{
      "scriptId":"u41"},
    "2718d630066b4eeab808f9fb4b5464ef":{
      "scriptId":"u42"},
    "8a661b64ea0b4bcf96e2c77512d0beba":{
      "scriptId":"u43"},
    "987d21211c1d4bfdab2f10da636264b2":{
      "scriptId":"u44"},
    "c5b724e8c0b843208bf8a5184ea02705":{
      "scriptId":"u45"},
    "d84b1604b4e14571ab8e4a89ac068ba8":{
      "scriptId":"u46"},
    "16acd6e95b1b49fcb3e6760616d1a65f":{
      "scriptId":"u47"},
    "8eaf8901f25240d4b18f914450e0f2d1":{
      "scriptId":"u48"},
    "3c9566e53e014e1fb3c7a410890bd946":{
      "scriptId":"u49"},
    "a78c2962a6004b48ba821d9815c992ea":{
      "scriptId":"u50"},
    "5a8684c78d2b4d9a9b1eb87bca1aa21e":{
      "scriptId":"u51"},
    "f0b4ce689c25496891e9ed6c83f25eac":{
      "scriptId":"u52"},
    "4cd2f81fd6324a009d2feb78a393afdd":{
      "scriptId":"u53"},
    "387a11cfaebc4deea01bf12de6fed64b":{
      "scriptId":"u54"},
    "1e816eb20e4c4db78b9db53840ed232c":{
      "scriptId":"u55"},
    "1ef64eebb69c47618df5d36e1d6e41ff":{
      "scriptId":"u56"},
    "4e2e419e4d1d4643aba75f72c82650e9":{
      "scriptId":"u57"},
    "2b277a9b5cf5438a89f9ae262aa6cbdd":{
      "scriptId":"u58"},
    "aeb36e8826fe43a8ac79af46d10624a8":{
      "scriptId":"u59"},
    "31c5c797ae474fa2a40001ea864f746b":{
      "scriptId":"u60"},
    "dc2c08d1360649d89af1504ca03bcf12":{
      "scriptId":"u61"},
    "9e37d87eca364641af466a3dc3662a22":{
      "scriptId":"u62"}}});