$axure.loadCurrentPage({
  "url":"机票酒店价格设置.html",
  "generationDate":new Date(1419937540962.78),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ae00c61a4e8647549bc771e733c46137",
    "type":"Axure:Page",
    "name":"机票酒店价格设置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"39bb51d235e042228bdf37b5fce23dfb",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"c0a6f8e65f9843a4bd1f1d0f4546bc5c"},
{
          "id":"c4953cff338c4c8286bda2b8aa80a31c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":85},
            "size":{
              "width":1209,
              "height":175}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"819ae9655f8044508f25b3a248448e78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":85},
                "size":{
                  "width":1209,
                  "height":175}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店地面价格设置/u5.png"}},
{
          "id":"fc947cf290794a4fa5b967fd735048ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":200,
              "y":268},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"068e72f2456243ac8e80dcdb1f855f75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":200,
                  "y":268},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b58bce3c0c6841bc94dce19f8add6b6b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":266},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6547c61f617b4d2e8be8471264bea87c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":200,
              "y":303},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d327da30d52e484db6fe19b666dd3b30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":200,
                  "y":303},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2a8b8def9324d23b7a399b80a0368e0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":301},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ef6f61ae95384147b80f75d23330d740",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":466,
              "y":371},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"01b6c224515241f5b78af219e638dd83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":203,
              "y":226},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f0c52fe2322473793315e018592d34d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":203,
                  "y":226},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"620240419feb46e5ba330656e9f74af6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":313,
              "y":218},
            "size":{
              "width":252,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94559f3890f44f7683cd4b15f89218f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":313,
                  "y":218},
                "size":{
                  "width":252,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店地面价格设置/u16.png"}},
{
          "id":"dd5fb570c9164c3483d7fc3100ac6b81",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":200,
              "y":335},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a83df315d2a943deaf8eed59566440be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":200,
                  "y":335},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a10218474b14eafa9dc7c85f3e5bd0a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":335},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"577736ad171b4867882443cf0ab43445",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":370},
            "size":{
              "width":130,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3968f9ef787442ffae4fbfafb6719db2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":200,
              "y":370},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1474343110d74614a9d9c29d6955e233",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":200,
                  "y":370},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"73af2c97574e4e5580e0ffc2e60aaf8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":603,
              "y":346},
            "size":{
              "width":647,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8375d4a0bb5444338c5c7bb574765b0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":603,
                  "y":346},
                "size":{
                  "width":647,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c27232216164321a24f97855028b0c0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":1757},
            "size":{
              "width":1130,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/酒店地面价格设置/u26_line.png"}},
{
          "id":"dfe0113fea1a449f91fda95665fdef76",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":1744},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2fcbedadadf4867a4e2decaaf2248f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":1744},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f3f84fbef9c74290a1996f4612a95b42",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":146,
              "y":1817},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"284598ed7dad492f8493479140b35aa0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":146,
                  "y":1817},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e4c1198c5a14dfab2cece814b944d30",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":266,
              "y":1815},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b2412385d3284e94a1498b6173243ebf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":146,
              "y":1894},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"034dbf37f182430bafd692fb76604f65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":146,
                  "y":1894},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9e25ced26494bb398ec937ff3855e68",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":266,
              "y":1892},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"475bb35b3c954c6d98f801cc1c0735ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":146,
              "y":1929},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8215e7f340049da83778cbd38c2b89b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":146,
                  "y":1929},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7401002f58043fd804524b38c2e9405",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":266,
              "y":1927},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0187929c0c984a5d8178c86fb879dd10",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":146,
              "y":1964},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e0efba711d3448e90ca9feae586d34d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":146,
                  "y":1964},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc5f83291bdd41aebc4cc26293abcdae",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":266,
              "y":1962},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e32d8899b0a14e4ba958628d460c708c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":513,
              "y":1805},
            "size":{
              "width":40,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e31bc07ce8949d1a3784a3759a8838a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":513,
                  "y":1805},
                "size":{
                  "width":40,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 交通套餐+,<br>交通套餐ID,<br>txt交通套餐ID,<br>交通套餐份数,<br>txt交通套餐份数",
                      "objectsToFades":[{
                          "objectPath":["e0c481f17c544da1875d9e45ca08df91"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f616b80ee95248bd8d4677772a72e4b7"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["654a04aaf2d044e1b262d0badf92fe37"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["78c200332d09436782d87eaa350ce431"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f5c70baa0a8c49989985db11cac4ea5c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/酒店地面价格设置/u47.png"}},
{
          "id":"62f6fa3eab1a4486bb2dc7872ec0675a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":403,
              "y":1813},
            "size":{
              "width":57,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82e74696b9094c93be31a8e64e41d8e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":403,
                  "y":1813},
                "size":{
                  "width":57,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"63d91f1c5aa14e07b890b6d24864e7a1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":461,
              "y":1811},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f545143f84124aa482a0bc7b0861b273",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":513,
              "y":1885},
            "size":{
              "width":40,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ce78cee85ab4d5e9a79022214696b45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":513,
                  "y":1885},
                "size":{
                  "width":40,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/酒店地面价格设置/u47.png"}},
{
          "id":"2acb1552fcd84e9ba9c97bee3a6e06f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":403,
              "y":1893},
            "size":{
              "width":57,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b06ddd9d1984abab751e4d1120d6ee6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":403,
                  "y":1893},
                "size":{
                  "width":57,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38dd97e9cada473ea86b260269e65857",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":461,
              "y":1891},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f450ab23938247cd82b212c858c53028",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":514,
              "y":1919},
            "size":{
              "width":40,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de33265e0b134ac89b14f1bc7ee36276",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":514,
                  "y":1919},
                "size":{
                  "width":40,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/酒店地面价格设置/u47.png"}},
{
          "id":"4bd9d74f4cc441d7a9e265a593199b2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":404,
              "y":1927},
            "size":{
              "width":57,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ae3ffb69c2e4bde84e8a0abbac4a108",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":404,
                  "y":1927},
                "size":{
                  "width":57,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e071db71a6844680938f98ba423849e0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":462,
              "y":1925},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"550c5a4e3f7b4e87b5d9948061874ae6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":514,
              "y":1957},
            "size":{
              "width":40,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b5731e95fcd401b9a7e489502c22b5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":514,
                  "y":1957},
                "size":{
                  "width":40,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/酒店地面价格设置/u47.png"}},
{
          "id":"2d003dd5b1f848579abea7a8a122bd70",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":404,
              "y":1965},
            "size":{
              "width":57,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09c168cea70c4b7b99c32911f29a8627",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":404,
                  "y":1965},
                "size":{
                  "width":57,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6109e62f07e54510b900ea5b585501a0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":462,
              "y":1963},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f616b80ee95248bd8d4677772a72e4b7",
          "label":"交通套餐ID",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":146,
              "y":1855},
            "size":{
              "width":94,
              "height":26},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"960ea2eb65794d6d8674158ee535a4db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":146,
                  "y":1855},
                "size":{
                  "width":94,
                  "height":26},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"654a04aaf2d044e1b262d0badf92fe37",
          "label":"txt交通套餐ID",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "location":{
              "x":266,
              "y":1855},
            "size":{
              "width":127,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"e0c481f17c544da1875d9e45ca08df91",
          "label":"交通套餐+",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":513,
              "y":1845},
            "size":{
              "width":40,
              "height":35},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"064502d37b8b4c5ba41d56c7d250a6ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":513,
                  "y":1845},
                "size":{
                  "width":40,
                  "height":35},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/酒店地面价格设置/u47.png"}},
{
          "id":"78c200332d09436782d87eaa350ce431",
          "label":"交通套餐份数",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":403,
              "y":1855},
            "size":{
              "width":57,
              "height":26},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09bf02c607f346909cd21be25c19a4fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":403,
                  "y":1855},
                "size":{
                  "width":57,
                  "height":26},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5c70baa0a8c49989985db11cac4ea5c",
          "label":"txt交通套餐份数",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "location":{
              "x":461,
              "y":1855},
            "size":{
              "width":40,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"d166d49a56034d1f9fc1784bc4e47e7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":174,
              "y":2003},
            "size":{
              "width":94,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b29414af7e9410b8ce5bb4016adadb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":174,
                  "y":2003},
                "size":{
                  "width":94,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb0666c84d8343998354541b74447a4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":174,
              "y":2034},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d99998e9a4f4110a4022a7431048b3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":174,
                  "y":2034},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ee1fcba9078424b9a0b93bc59003575",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":174,
              "y":2066},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4199aa55b40d40728717e3081802d71a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":174,
                  "y":2066},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c9d13e3b5c84011abd8b33795c3c501",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":389,
              "y":2000},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88b12881581e4520a374a6adc5017658",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":389,
                  "y":2000},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"757e4457de3b492b89da084d58d0c4fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":396,
              "y":2035},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15246cd7a0f44e3bac5bc336262a6a64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":396,
                  "y":2035},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c916567874cd4719a4a5d5bee19aa9c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":397,
              "y":2067},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"391a1dab6f244a42bc992ae241daf356",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":397,
                  "y":2067},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d89e1c0c94e74ddfacc100a7e86b5951",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":452},
            "size":{
              "width":1183,
              "height":417}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b943ca0e805e43db859e3b71f3824836",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":452},
                "size":{
                  "width":1183,
                  "height":417}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机票地面价格设置/u81.png"}},
{
          "id":"5a96eac8a5294c9fa0b63868b6dfd91e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":434},
            "size":{
              "width":1130,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/酒店地面价格设置/u26_line.png"}},
{
          "id":"0c7e08a8ebcd44a7a82734022136cdc4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":420},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab38107ec8ca455a9bc49d84db751fc7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":420},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4755b19a452d42218b8b8fc31589eea1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":874},
            "size":{
              "width":1159,
              "height":464}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da898901d21945098f914b7812b9111f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":874},
                "size":{
                  "width":1159,
                  "height":464}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机票地面价格设置/u86.png"}},
{
          "id":"8dee4a2c1366452fb0c61aaa5808e04a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":259,
              "y":1335},
            "size":{
              "width":1057,
              "height":385}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e6cd55a99c94879b0e1820a81b2754a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":259,
                  "y":1335},
                "size":{
                  "width":1057,
                  "height":385}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机票地面价格设置/u88.png"}},
{
          "id":"77a4a3b883cf4672be1470f25c7fe84a",
          "label":"酒店套餐ID",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":147,
              "y":1775},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b63731b3e214e54a11906361d32b9df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":147,
                  "y":1775},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c14c57da81ee4c2ca92e28e6c3e2f152",
          "label":"txt酒店套餐ID",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":267,
              "y":1773},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e6bd7c65ccee4dc39eeb430b5a1b79bd",
          "label":"酒店套餐份数",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":405,
              "y":1777},
            "size":{
              "width":57,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1335387cf8184a9c8d8e11b6a4af2613",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":405,
                  "y":1777},
                "size":{
                  "width":57,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f87c8aa43524dee8e303d952eb4fd54",
          "label":"txt酒店套餐份数",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":461,
              "y":1774},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
    "c0a6f8e65f9843a4bd1f1d0f4546bc5c":{
      "packageId":"c0a6f8e65f9843a4bd1f1d0f4546bc5c",
      "type":"Axure:Master",
      "name":"产品管理",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"5024326008c74a3f90f4004ca3eb09ad",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":1364,
                "height":667}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3533708ddaf64d53ab22ac58fbcf7457",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1364,
                    "height":667}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/酒店/u1.png"}},
{
            "id":"b3d7ad7f6d44402fbfdfac4c0f1e8cb0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":140,
                "y":76},
              "size":{
                "width":1226,
                "height":591},
              "linePattern":"none"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b3e89a31a0f041cbbc6ef6f867f6e9ca",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":140,
                    "y":76},
                  "size":{
                    "width":1226,
                    "height":591},
                  "linePattern":"none"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/酒店/u3.png"}}]}}},
  "objectPaths":{
    "39bb51d235e042228bdf37b5fce23dfb":{
      "scriptId":"u0",
      "5024326008c74a3f90f4004ca3eb09ad":{
        "scriptId":"u1"},
      "3533708ddaf64d53ab22ac58fbcf7457":{
        "scriptId":"u2"},
      "b3d7ad7f6d44402fbfdfac4c0f1e8cb0":{
        "scriptId":"u3"},
      "b3e89a31a0f041cbbc6ef6f867f6e9ca":{
        "scriptId":"u4"}},
    "c4953cff338c4c8286bda2b8aa80a31c":{
      "scriptId":"u5"},
    "819ae9655f8044508f25b3a248448e78":{
      "scriptId":"u6"},
    "fc947cf290794a4fa5b967fd735048ab":{
      "scriptId":"u7"},
    "068e72f2456243ac8e80dcdb1f855f75":{
      "scriptId":"u8"},
    "b58bce3c0c6841bc94dce19f8add6b6b":{
      "scriptId":"u9"},
    "6547c61f617b4d2e8be8471264bea87c":{
      "scriptId":"u10"},
    "d327da30d52e484db6fe19b666dd3b30":{
      "scriptId":"u11"},
    "f2a8b8def9324d23b7a399b80a0368e0":{
      "scriptId":"u12"},
    "ef6f61ae95384147b80f75d23330d740":{
      "scriptId":"u13"},
    "01b6c224515241f5b78af219e638dd83":{
      "scriptId":"u14"},
    "4f0c52fe2322473793315e018592d34d":{
      "scriptId":"u15"},
    "620240419feb46e5ba330656e9f74af6":{
      "scriptId":"u16"},
    "94559f3890f44f7683cd4b15f89218f5":{
      "scriptId":"u17"},
    "dd5fb570c9164c3483d7fc3100ac6b81":{
      "scriptId":"u18"},
    "a83df315d2a943deaf8eed59566440be":{
      "scriptId":"u19"},
    "3a10218474b14eafa9dc7c85f3e5bd0a":{
      "scriptId":"u20"},
    "577736ad171b4867882443cf0ab43445":{
      "scriptId":"u21"},
    "3968f9ef787442ffae4fbfafb6719db2":{
      "scriptId":"u22"},
    "1474343110d74614a9d9c29d6955e233":{
      "scriptId":"u23"},
    "73af2c97574e4e5580e0ffc2e60aaf8e":{
      "scriptId":"u24"},
    "8375d4a0bb5444338c5c7bb574765b0f":{
      "scriptId":"u25"},
    "4c27232216164321a24f97855028b0c0":{
      "scriptId":"u26"},
    "dfe0113fea1a449f91fda95665fdef76":{
      "scriptId":"u27"},
    "e2fcbedadadf4867a4e2decaaf2248f4":{
      "scriptId":"u28"},
    "f3f84fbef9c74290a1996f4612a95b42":{
      "scriptId":"u29"},
    "284598ed7dad492f8493479140b35aa0":{
      "scriptId":"u30"},
    "2e4c1198c5a14dfab2cece814b944d30":{
      "scriptId":"u31"},
    "b2412385d3284e94a1498b6173243ebf":{
      "scriptId":"u32"},
    "034dbf37f182430bafd692fb76604f65":{
      "scriptId":"u33"},
    "b9e25ced26494bb398ec937ff3855e68":{
      "scriptId":"u34"},
    "475bb35b3c954c6d98f801cc1c0735ae":{
      "scriptId":"u35"},
    "c8215e7f340049da83778cbd38c2b89b":{
      "scriptId":"u36"},
    "b7401002f58043fd804524b38c2e9405":{
      "scriptId":"u37"},
    "0187929c0c984a5d8178c86fb879dd10":{
      "scriptId":"u38"},
    "7e0efba711d3448e90ca9feae586d34d":{
      "scriptId":"u39"},
    "bc5f83291bdd41aebc4cc26293abcdae":{
      "scriptId":"u40"},
    "e32d8899b0a14e4ba958628d460c708c":{
      "scriptId":"u41"},
    "4e31bc07ce8949d1a3784a3759a8838a":{
      "scriptId":"u42"},
    "62f6fa3eab1a4486bb2dc7872ec0675a":{
      "scriptId":"u43"},
    "82e74696b9094c93be31a8e64e41d8e9":{
      "scriptId":"u44"},
    "63d91f1c5aa14e07b890b6d24864e7a1":{
      "scriptId":"u45"},
    "f545143f84124aa482a0bc7b0861b273":{
      "scriptId":"u46"},
    "8ce78cee85ab4d5e9a79022214696b45":{
      "scriptId":"u47"},
    "2acb1552fcd84e9ba9c97bee3a6e06f4":{
      "scriptId":"u48"},
    "3b06ddd9d1984abab751e4d1120d6ee6":{
      "scriptId":"u49"},
    "38dd97e9cada473ea86b260269e65857":{
      "scriptId":"u50"},
    "f450ab23938247cd82b212c858c53028":{
      "scriptId":"u51"},
    "de33265e0b134ac89b14f1bc7ee36276":{
      "scriptId":"u52"},
    "4bd9d74f4cc441d7a9e265a593199b2a":{
      "scriptId":"u53"},
    "3ae3ffb69c2e4bde84e8a0abbac4a108":{
      "scriptId":"u54"},
    "e071db71a6844680938f98ba423849e0":{
      "scriptId":"u55"},
    "550c5a4e3f7b4e87b5d9948061874ae6":{
      "scriptId":"u56"},
    "6b5731e95fcd401b9a7e489502c22b5f":{
      "scriptId":"u57"},
    "2d003dd5b1f848579abea7a8a122bd70":{
      "scriptId":"u58"},
    "09c168cea70c4b7b99c32911f29a8627":{
      "scriptId":"u59"},
    "6109e62f07e54510b900ea5b585501a0":{
      "scriptId":"u60"},
    "f616b80ee95248bd8d4677772a72e4b7":{
      "scriptId":"u61"},
    "960ea2eb65794d6d8674158ee535a4db":{
      "scriptId":"u62"},
    "654a04aaf2d044e1b262d0badf92fe37":{
      "scriptId":"u63"},
    "e0c481f17c544da1875d9e45ca08df91":{
      "scriptId":"u64"},
    "064502d37b8b4c5ba41d56c7d250a6ac":{
      "scriptId":"u65"},
    "78c200332d09436782d87eaa350ce431":{
      "scriptId":"u66"},
    "09bf02c607f346909cd21be25c19a4fe":{
      "scriptId":"u67"},
    "f5c70baa0a8c49989985db11cac4ea5c":{
      "scriptId":"u68"},
    "d166d49a56034d1f9fc1784bc4e47e7f":{
      "scriptId":"u69"},
    "1b29414af7e9410b8ce5bb4016adadb4":{
      "scriptId":"u70"},
    "bb0666c84d8343998354541b74447a4e":{
      "scriptId":"u71"},
    "1d99998e9a4f4110a4022a7431048b3f":{
      "scriptId":"u72"},
    "8ee1fcba9078424b9a0b93bc59003575":{
      "scriptId":"u73"},
    "4199aa55b40d40728717e3081802d71a":{
      "scriptId":"u74"},
    "3c9d13e3b5c84011abd8b33795c3c501":{
      "scriptId":"u75"},
    "88b12881581e4520a374a6adc5017658":{
      "scriptId":"u76"},
    "757e4457de3b492b89da084d58d0c4fc":{
      "scriptId":"u77"},
    "15246cd7a0f44e3bac5bc336262a6a64":{
      "scriptId":"u78"},
    "c916567874cd4719a4a5d5bee19aa9c6":{
      "scriptId":"u79"},
    "391a1dab6f244a42bc992ae241daf356":{
      "scriptId":"u80"},
    "d89e1c0c94e74ddfacc100a7e86b5951":{
      "scriptId":"u81"},
    "b943ca0e805e43db859e3b71f3824836":{
      "scriptId":"u82"},
    "5a96eac8a5294c9fa0b63868b6dfd91e":{
      "scriptId":"u83"},
    "0c7e08a8ebcd44a7a82734022136cdc4":{
      "scriptId":"u84"},
    "ab38107ec8ca455a9bc49d84db751fc7":{
      "scriptId":"u85"},
    "4755b19a452d42218b8b8fc31589eea1":{
      "scriptId":"u86"},
    "da898901d21945098f914b7812b9111f":{
      "scriptId":"u87"},
    "8dee4a2c1366452fb0c61aaa5808e04a":{
      "scriptId":"u88"},
    "1e6cd55a99c94879b0e1820a81b2754a":{
      "scriptId":"u89"},
    "77a4a3b883cf4672be1470f25c7fe84a":{
      "scriptId":"u90"},
    "5b63731b3e214e54a11906361d32b9df":{
      "scriptId":"u91"},
    "c14c57da81ee4c2ca92e28e6c3e2f152":{
      "scriptId":"u92"},
    "e6bd7c65ccee4dc39eeb430b5a1b79bd":{
      "scriptId":"u93"},
    "1335387cf8184a9c8d8e11b6a4af2613":{
      "scriptId":"u94"},
    "1f87c8aa43524dee8e303d952eb4fd54":{
      "scriptId":"u95"}}});