$axure.loadCurrentPage({
  "url":"机票地面价格设置.html",
  "generationDate":new Date(1419937540689.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"483ac03f3c9549c792f88715261493fb",
    "type":"Axure:Page",
    "name":"机票地面价格设置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"df4b605edfad47f0a1711649945f0bad",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"c0a6f8e65f9843a4bd1f1d0f4546bc5c"},
{
          "id":"b1f56bdfac014d74aa9b288fb0e6b831",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":85},
            "size":{
              "width":1209,
              "height":175}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13f2e2df08d541e2a5743c8e04898b8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":85},
                "size":{
                  "width":1209,
                  "height":175}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店地面价格设置/u5.png"}},
{
          "id":"6a74a1d1a2ba4b5192b02392b1c8bb0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":200,
              "y":268},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1508fa972dbd4a7fa04a854f8b1ecab9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":200,
                  "y":268},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd8e7cf7405c4f9b8cf59d49686d6e18",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":266},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"be5a1e8029324c1287df55051320397c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":200,
              "y":303},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"366fec72211945f4b03a6ab579ff02dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":200,
                  "y":303},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"32761d1f8edd486fa4cf0f2440d6b34e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":301},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"17b0cca21cb94c1590c32feac02be9c1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":466,
              "y":371},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"00bbcc8b6ea9465b94bbe671200fb75a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":203,
              "y":226},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bce67f30f6734b2bbf3640d9f1500698",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":203,
                  "y":226},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"52ffbd479d274d16b1b5b1e4caf9565a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":313,
              "y":218},
            "size":{
              "width":252,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"540cf250935a42b2a7930bbe1ccf3086",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":313,
                  "y":218},
                "size":{
                  "width":252,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店地面价格设置/u16.png"}},
{
          "id":"b1186b942a2447ca97f61c7bb99953f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":200,
              "y":335},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c342cc4fb6754197bc378a0cb6ff7e57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":200,
                  "y":335},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e00ae3784f742c88f463fa200dcd529",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":335},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c84ee036950b480cbbbaa0a0c2b7a379",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":370},
            "size":{
              "width":130,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ea11427228d14dba8a07c032e7d34e83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":200,
              "y":370},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1f7e35d5ce14830adb7c132062fa3c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":200,
                  "y":370},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"770d913710ea48f08153c1ca28d83412",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":603,
              "y":346},
            "size":{
              "width":647,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ee2bb0a90e94974bc473c86777e0aab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":603,
                  "y":346},
                "size":{
                  "width":647,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a562e53c75fd497799fd151f433b5ae3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":1757},
            "size":{
              "width":1130,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/酒店地面价格设置/u26_line.png"}},
{
          "id":"a817bc98b79a40d9b0e3f95d66f5f930",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":1744},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f16513edef7943d0a7d21ec6c6dbf92e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":1744},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ba36159d1fa4d6e99dd6f14ccce3bee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":146,
              "y":1786},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f85c5a6db9d34aa4ab348a9a8c4a014b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":146,
                  "y":1786},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e7a605924464f3894ede1c88bcd11b3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":266,
              "y":1784},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d1479e2e4afd487f94850095c5083c3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":146,
              "y":1863},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"638dc60434234c4e81e411e657365a1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":146,
                  "y":1863},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"67eed9604bb042d2886c1ef3b2d08747",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":266,
              "y":1861},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"027334afc580484eb0a9fb03c617991f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":146,
              "y":1898},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99d703fdbefc4dc6afbfa09beadef829",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":146,
                  "y":1898},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dcaff87bc28943db927cd8759a423b0a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":266,
              "y":1896},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c1861aef7b1943a89dcd9bd810f130e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":146,
              "y":1933},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0427b4d8d6704981a073c0e3a6ab1e64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":146,
                  "y":1933},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26e39214c4e848319d621b8e63fe212b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":266,
              "y":1931},
            "size":{
              "width":127,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ea73321dd35a492a9d8434600628218c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":513,
              "y":1774},
            "size":{
              "width":40,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"914a393bfc1545b3987fd2ee61a152f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":513,
                  "y":1774},
                "size":{
                  "width":40,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 交通套餐+,<br>交通套餐ID,<br>txt交通套餐ID,<br>交通套餐份数,<br>txt交通套餐份数",
                      "objectsToFades":[{
                          "objectPath":["c730672e0479432aa96e0af78f0b0f3e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["5afd8c9ad03b46f2a59cca1c0937750c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["3cb89aead4cf4fe9841360cc87506089"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["d973a9f5a9fb4f22be58720847c2011e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["0fc69b6b7fa84b119a3b7a85dd1af773"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/酒店地面价格设置/u47.png"}},
{
          "id":"5977b68e4fa84bcf9b2fe09cc9441479",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":403,
              "y":1782},
            "size":{
              "width":57,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3078462bed8942cf87ed29d19d1fae2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":403,
                  "y":1782},
                "size":{
                  "width":57,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"275626e0bdef4884bce21aee514e5bc6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":461,
              "y":1780},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"24d109ee944c481da914ff375ef44987",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":513,
              "y":1854},
            "size":{
              "width":40,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1d0b59eab9644d78734d2ed5dbe3200",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":513,
                  "y":1854},
                "size":{
                  "width":40,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/酒店地面价格设置/u47.png"}},
{
          "id":"b51878d6f3124deabfb61be15214b2e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":403,
              "y":1862},
            "size":{
              "width":57,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de228aef56f64b1181335d48cf578a9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":403,
                  "y":1862},
                "size":{
                  "width":57,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a43d39e76bd24240a62d438fa5a444b3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":461,
              "y":1860},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1e4f634719614eecbec51dbc9dc7440b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":514,
              "y":1888},
            "size":{
              "width":40,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54b26bbb699f4c8c9812639d9a42a201",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":514,
                  "y":1888},
                "size":{
                  "width":40,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/酒店地面价格设置/u47.png"}},
{
          "id":"adbb5ef617df4a07845bf65b22a6821c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":404,
              "y":1896},
            "size":{
              "width":57,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b23c0f017c2c45b2be569cc03fad4898",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":404,
                  "y":1896},
                "size":{
                  "width":57,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23e8362e2d2e4ce28b41732e671042d3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":462,
              "y":1894},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4d7616e4c599493d840f9bd2fb106f45",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":514,
              "y":1926},
            "size":{
              "width":40,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2700f9d176c4229acae59faa9111fbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":514,
                  "y":1926},
                "size":{
                  "width":40,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/酒店地面价格设置/u47.png"}},
{
          "id":"d3b4014d4b8e45e3abb4e262f8d61dea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":404,
              "y":1934},
            "size":{
              "width":57,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50558f01c5e2432e8bacb6a5488b59d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":404,
                  "y":1934},
                "size":{
                  "width":57,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7ff760d483143c785eb13cd361ef247",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":462,
              "y":1932},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5afd8c9ad03b46f2a59cca1c0937750c",
          "label":"交通套餐ID",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":146,
              "y":1824},
            "size":{
              "width":94,
              "height":26},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adcb96006d83401eb29516d0a35482f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":146,
                  "y":1824},
                "size":{
                  "width":94,
                  "height":26},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3cb89aead4cf4fe9841360cc87506089",
          "label":"txt交通套餐ID",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "location":{
              "x":266,
              "y":1824},
            "size":{
              "width":127,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"c730672e0479432aa96e0af78f0b0f3e",
          "label":"交通套餐+",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":513,
              "y":1814},
            "size":{
              "width":40,
              "height":35},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19d35efc1b184aa3a524a46b9273af5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":513,
                  "y":1814},
                "size":{
                  "width":40,
                  "height":35},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/酒店地面价格设置/u47.png"}},
{
          "id":"d973a9f5a9fb4f22be58720847c2011e",
          "label":"交通套餐份数",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":403,
              "y":1824},
            "size":{
              "width":57,
              "height":26},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c44493311a84793878780d22b903351",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":403,
                  "y":1824},
                "size":{
                  "width":57,
                  "height":26},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0fc69b6b7fa84b119a3b7a85dd1af773",
          "label":"txt交通套餐份数",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "location":{
              "x":461,
              "y":1824},
            "size":{
              "width":40,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"a1bc633ce3cb43f0b7fe2f697b78c5fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":174,
              "y":1972},
            "size":{
              "width":94,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e68919453b3a48e495fa2363892ce555",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":174,
                  "y":1972},
                "size":{
                  "width":94,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7638bc54e32443d485d6002488a4ac54",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":174,
              "y":2003},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ed3f24d23f4422e861a1b3d152d9314",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":174,
                  "y":2003},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"610f38f512e44d6fb5982c59a7d20964",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":174,
              "y":2035},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44062cc4d3ca4b88ad358b89ba608a51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":174,
                  "y":2035},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d81aeb6c5b3f4ffd93996dada10c8d6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":389,
              "y":1969},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a9a2b704f5643f19c96dec6c858ef27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":389,
                  "y":1969},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5176114db9a64509990575666d6888f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":396,
              "y":2004},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1dc661169d074cc8a2915eed04f282b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":396,
                  "y":2004},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"36373c5325624f1f98b3441ed0362154",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":397,
              "y":2036},
            "size":{
              "width":94,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7297383e3181475ebb34d9163ff561ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":397,
                  "y":2036},
                "size":{
                  "width":94,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26c688f82e1c4f26b499373883320828",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":452},
            "size":{
              "width":1183,
              "height":417}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e42316260dc84631a1e34d70fa943c0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":452},
                "size":{
                  "width":1183,
                  "height":417}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机票地面价格设置/u81.png"}},
{
          "id":"5d3d85aa16404709b1275a601f00bda2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":434},
            "size":{
              "width":1130,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/酒店地面价格设置/u26_line.png"}},
{
          "id":"cea015037b534ffa82d9873997863db5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":420},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3a570604bc24a1493c4ae0a2e29004d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":420},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66182fed14a44e92b74c6a161ee60358",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":874},
            "size":{
              "width":1159,
              "height":464}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6548b405a7ba45a2955f19c0fae39fc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":874},
                "size":{
                  "width":1159,
                  "height":464}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机票地面价格设置/u86.png"}},
{
          "id":"0e6e71b0d23f4082b307954e5c17a529",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":259,
              "y":1335},
            "size":{
              "width":1057,
              "height":385}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e400dab8063d40e39813a91b86579795",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":259,
                  "y":1335},
                "size":{
                  "width":1057,
                  "height":385}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机票地面价格设置/u88.png"}}]}},
  "masters":{
    "c0a6f8e65f9843a4bd1f1d0f4546bc5c":{
      "packageId":"c0a6f8e65f9843a4bd1f1d0f4546bc5c",
      "type":"Axure:Master",
      "name":"产品管理",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"5024326008c74a3f90f4004ca3eb09ad",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":1364,
                "height":667}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3533708ddaf64d53ab22ac58fbcf7457",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1364,
                    "height":667}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/酒店/u1.png"}},
{
            "id":"b3d7ad7f6d44402fbfdfac4c0f1e8cb0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":140,
                "y":76},
              "size":{
                "width":1226,
                "height":591},
              "linePattern":"none"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b3e89a31a0f041cbbc6ef6f867f6e9ca",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":140,
                    "y":76},
                  "size":{
                    "width":1226,
                    "height":591},
                  "linePattern":"none"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/酒店/u3.png"}}]}}},
  "objectPaths":{
    "df4b605edfad47f0a1711649945f0bad":{
      "scriptId":"u0",
      "5024326008c74a3f90f4004ca3eb09ad":{
        "scriptId":"u1"},
      "3533708ddaf64d53ab22ac58fbcf7457":{
        "scriptId":"u2"},
      "b3d7ad7f6d44402fbfdfac4c0f1e8cb0":{
        "scriptId":"u3"},
      "b3e89a31a0f041cbbc6ef6f867f6e9ca":{
        "scriptId":"u4"}},
    "b1f56bdfac014d74aa9b288fb0e6b831":{
      "scriptId":"u5"},
    "13f2e2df08d541e2a5743c8e04898b8f":{
      "scriptId":"u6"},
    "6a74a1d1a2ba4b5192b02392b1c8bb0f":{
      "scriptId":"u7"},
    "1508fa972dbd4a7fa04a854f8b1ecab9":{
      "scriptId":"u8"},
    "cd8e7cf7405c4f9b8cf59d49686d6e18":{
      "scriptId":"u9"},
    "be5a1e8029324c1287df55051320397c":{
      "scriptId":"u10"},
    "366fec72211945f4b03a6ab579ff02dd":{
      "scriptId":"u11"},
    "32761d1f8edd486fa4cf0f2440d6b34e":{
      "scriptId":"u12"},
    "17b0cca21cb94c1590c32feac02be9c1":{
      "scriptId":"u13"},
    "00bbcc8b6ea9465b94bbe671200fb75a":{
      "scriptId":"u14"},
    "bce67f30f6734b2bbf3640d9f1500698":{
      "scriptId":"u15"},
    "52ffbd479d274d16b1b5b1e4caf9565a":{
      "scriptId":"u16"},
    "540cf250935a42b2a7930bbe1ccf3086":{
      "scriptId":"u17"},
    "b1186b942a2447ca97f61c7bb99953f9":{
      "scriptId":"u18"},
    "c342cc4fb6754197bc378a0cb6ff7e57":{
      "scriptId":"u19"},
    "8e00ae3784f742c88f463fa200dcd529":{
      "scriptId":"u20"},
    "c84ee036950b480cbbbaa0a0c2b7a379":{
      "scriptId":"u21"},
    "ea11427228d14dba8a07c032e7d34e83":{
      "scriptId":"u22"},
    "e1f7e35d5ce14830adb7c132062fa3c3":{
      "scriptId":"u23"},
    "770d913710ea48f08153c1ca28d83412":{
      "scriptId":"u24"},
    "4ee2bb0a90e94974bc473c86777e0aab":{
      "scriptId":"u25"},
    "a562e53c75fd497799fd151f433b5ae3":{
      "scriptId":"u26"},
    "a817bc98b79a40d9b0e3f95d66f5f930":{
      "scriptId":"u27"},
    "f16513edef7943d0a7d21ec6c6dbf92e":{
      "scriptId":"u28"},
    "6ba36159d1fa4d6e99dd6f14ccce3bee":{
      "scriptId":"u29"},
    "f85c5a6db9d34aa4ab348a9a8c4a014b":{
      "scriptId":"u30"},
    "9e7a605924464f3894ede1c88bcd11b3":{
      "scriptId":"u31"},
    "d1479e2e4afd487f94850095c5083c3f":{
      "scriptId":"u32"},
    "638dc60434234c4e81e411e657365a1e":{
      "scriptId":"u33"},
    "67eed9604bb042d2886c1ef3b2d08747":{
      "scriptId":"u34"},
    "027334afc580484eb0a9fb03c617991f":{
      "scriptId":"u35"},
    "99d703fdbefc4dc6afbfa09beadef829":{
      "scriptId":"u36"},
    "dcaff87bc28943db927cd8759a423b0a":{
      "scriptId":"u37"},
    "c1861aef7b1943a89dcd9bd810f130e0":{
      "scriptId":"u38"},
    "0427b4d8d6704981a073c0e3a6ab1e64":{
      "scriptId":"u39"},
    "26e39214c4e848319d621b8e63fe212b":{
      "scriptId":"u40"},
    "ea73321dd35a492a9d8434600628218c":{
      "scriptId":"u41"},
    "914a393bfc1545b3987fd2ee61a152f5":{
      "scriptId":"u42"},
    "5977b68e4fa84bcf9b2fe09cc9441479":{
      "scriptId":"u43"},
    "3078462bed8942cf87ed29d19d1fae2f":{
      "scriptId":"u44"},
    "275626e0bdef4884bce21aee514e5bc6":{
      "scriptId":"u45"},
    "24d109ee944c481da914ff375ef44987":{
      "scriptId":"u46"},
    "a1d0b59eab9644d78734d2ed5dbe3200":{
      "scriptId":"u47"},
    "b51878d6f3124deabfb61be15214b2e7":{
      "scriptId":"u48"},
    "de228aef56f64b1181335d48cf578a9a":{
      "scriptId":"u49"},
    "a43d39e76bd24240a62d438fa5a444b3":{
      "scriptId":"u50"},
    "1e4f634719614eecbec51dbc9dc7440b":{
      "scriptId":"u51"},
    "54b26bbb699f4c8c9812639d9a42a201":{
      "scriptId":"u52"},
    "adbb5ef617df4a07845bf65b22a6821c":{
      "scriptId":"u53"},
    "b23c0f017c2c45b2be569cc03fad4898":{
      "scriptId":"u54"},
    "23e8362e2d2e4ce28b41732e671042d3":{
      "scriptId":"u55"},
    "4d7616e4c599493d840f9bd2fb106f45":{
      "scriptId":"u56"},
    "d2700f9d176c4229acae59faa9111fbf":{
      "scriptId":"u57"},
    "d3b4014d4b8e45e3abb4e262f8d61dea":{
      "scriptId":"u58"},
    "50558f01c5e2432e8bacb6a5488b59d3":{
      "scriptId":"u59"},
    "b7ff760d483143c785eb13cd361ef247":{
      "scriptId":"u60"},
    "5afd8c9ad03b46f2a59cca1c0937750c":{
      "scriptId":"u61"},
    "adcb96006d83401eb29516d0a35482f1":{
      "scriptId":"u62"},
    "3cb89aead4cf4fe9841360cc87506089":{
      "scriptId":"u63"},
    "c730672e0479432aa96e0af78f0b0f3e":{
      "scriptId":"u64"},
    "19d35efc1b184aa3a524a46b9273af5b":{
      "scriptId":"u65"},
    "d973a9f5a9fb4f22be58720847c2011e":{
      "scriptId":"u66"},
    "8c44493311a84793878780d22b903351":{
      "scriptId":"u67"},
    "0fc69b6b7fa84b119a3b7a85dd1af773":{
      "scriptId":"u68"},
    "a1bc633ce3cb43f0b7fe2f697b78c5fd":{
      "scriptId":"u69"},
    "e68919453b3a48e495fa2363892ce555":{
      "scriptId":"u70"},
    "7638bc54e32443d485d6002488a4ac54":{
      "scriptId":"u71"},
    "1ed3f24d23f4422e861a1b3d152d9314":{
      "scriptId":"u72"},
    "610f38f512e44d6fb5982c59a7d20964":{
      "scriptId":"u73"},
    "44062cc4d3ca4b88ad358b89ba608a51":{
      "scriptId":"u74"},
    "d81aeb6c5b3f4ffd93996dada10c8d6d":{
      "scriptId":"u75"},
    "9a9a2b704f5643f19c96dec6c858ef27":{
      "scriptId":"u76"},
    "5176114db9a64509990575666d6888f9":{
      "scriptId":"u77"},
    "1dc661169d074cc8a2915eed04f282b4":{
      "scriptId":"u78"},
    "36373c5325624f1f98b3441ed0362154":{
      "scriptId":"u79"},
    "7297383e3181475ebb34d9163ff561ac":{
      "scriptId":"u80"},
    "26c688f82e1c4f26b499373883320828":{
      "scriptId":"u81"},
    "e42316260dc84631a1e34d70fa943c0d":{
      "scriptId":"u82"},
    "5d3d85aa16404709b1275a601f00bda2":{
      "scriptId":"u83"},
    "cea015037b534ffa82d9873997863db5":{
      "scriptId":"u84"},
    "e3a570604bc24a1493c4ae0a2e29004d":{
      "scriptId":"u85"},
    "66182fed14a44e92b74c6a161ee60358":{
      "scriptId":"u86"},
    "6548b405a7ba45a2955f19c0fae39fc4":{
      "scriptId":"u87"},
    "0e6e71b0d23f4082b307954e5c17a529":{
      "scriptId":"u88"},
    "e400dab8063d40e39813a91b86579795":{
      "scriptId":"u89"}}});