$axure.loadCurrentPage({
  "url":"酒店_地面.html",
  "generationDate":new Date(1419937540309.74),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"910b83323df94c60a2d5d625d28cb1a1",
    "type":"Axure:Page",
    "name":"酒店+地面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5d6a717480f248bda00cb2c40f8af297",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"c0a6f8e65f9843a4bd1f1d0f4546bc5c"},
{
          "id":"ebed7bace75144b6b8b59bcbef2c43e1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":164,
              "y":86},
            "size":{
              "width":1192,
              "height":573}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a805771be51c4627bd31ca58be508dad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":164,
                  "y":86},
                "size":{
                  "width":1192,
                  "height":573}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店/u5.png"}},
{
          "id":"22727e756455415e8e5506e4724d909b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":167,
              "y":417},
            "size":{
              "width":1183,
              "height":294}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ad84368cd774defb45a32850c3330f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":167,
                  "y":417},
                "size":{
                  "width":1183,
                  "height":294}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店/u9.png"}},
{
          "id":"7842f877a34b4c8aa28bc7207d230b3a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":165,
              "y":496},
            "size":{
              "width":1187,
              "height":338}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1475e2f991d84713a7ec0ca810b98fa2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":165,
                  "y":496},
                "size":{
                  "width":1187,
                  "height":338}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店/u11.png"}},
{
          "id":"1d55a7c2b33a434698234b69cce5e18e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":162,
              "y":913},
            "size":{
              "width":1191,
              "height":362}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71fc513c19ce4ddf8f921d0c0774a2d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":162,
                  "y":913},
                "size":{
                  "width":1191,
                  "height":362}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店/u23.png"}},
{
          "id":"88e25e05b941422f8df900f90d952996",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":164,
              "y":1272},
            "size":{
              "width":1189,
              "height":478}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dd9ea69f77d4e6c890757d0f29e3961",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":164,
                  "y":1272},
                "size":{
                  "width":1189,
                  "height":478}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店/u25.png"}},
{
          "id":"b19c75706c294640a275eef0000e1fc2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":163,
              "y":829},
            "size":{
              "width":1191,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea99017dd72f41bc9e0ecf0bb58a552a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":163,
                  "y":829},
                "size":{
                  "width":1191,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店/u29.png"}},
{
          "id":"88f07d510ce448e19b0d0d2de85c39f5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":165,
              "y":255},
            "size":{
              "width":1187,
              "height":327}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5daa9d8657644f9191d5ae93c7a8462b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":165,
                  "y":255},
                "size":{
                  "width":1187,
                  "height":327}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店_地面/u17.png"}},
{
          "id":"ee3e1bb89550445f85878d851f41a9e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":217},
            "size":{
              "width":850,
              "height":35},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ffd489d6e2d458da0e2bee4fc3348ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":217},
                "size":{
                  "width":850,
                  "height":35},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店_地面/u19.png"}},
{
          "id":"feda9d9e9f6e4953ba4b918a0c9c78e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":234,
              "y":229},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7dff947e1168420aa6308b0aef6c983e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":234,
                  "y":229},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"947a219d4e6e4d0db5ec756027d7f3f0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":224},
            "size":{
              "width":176,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f574132c43f549d0ba1902e759c46172",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":520,
              "y":218},
            "size":{
              "width":300,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"969ba3b74f294597ad962dbe6498fa28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":520,
                  "y":218},
                "size":{
                  "width":300,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97200eef22bd454db4290ee9905f6c9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":735,
              "y":262},
            "size":{
              "width":270,
              "height":35},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eaadd7b7a9944638a5abb2a70874645e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":735,
                  "y":262},
                "size":{
                  "width":270,
                  "height":35},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店_地面/u26.png"}},
{
          "id":"91f36bf6ac2d4cec82681a2055a3a7ac",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":852,
              "y":263},
            "size":{
              "width":251,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee9bb7b7e7ed48809644353c09134dac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":852,
                  "y":263},
                "size":{
                  "width":251,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店_地面/u28.png"}},
{
          "id":"5194637f1d474c2e9e1261009f790b66",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":735,
              "y":267},
            "size":{
              "width":65,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"8bc4af3849fb42bcaca13c47b596d6b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":807,
              "y":270},
            "size":{
              "width":51,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb35206aac2c4066b0837cb42e8bd064",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":807,
                  "y":270},
                "size":{
                  "width":51,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"139ba8e2d0ca400e87abb1bbbccfd4a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":239,
              "y":510},
            "size":{
              "width":80,
              "height":25},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3dc10eeeb28420eb0346fe4f7e859e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":239,
                  "y":510},
                "size":{
                  "width":80,
                  "height":25},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店/u27.png"}},
{
          "id":"ef71128646e349d0a7f6a69c6f5c63f7",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":510},
            "size":{
              "width":78,
              "height":28}},
          "adaptiveStyles":{
}},
{
          "id":"b1522abb00d54d91a72991bcc2516d1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":549},
            "size":{
              "width":80,
              "height":25},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3ebf4ddbe234b8f9a0d077dbb71033e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":238,
                  "y":549},
                "size":{
                  "width":80,
                  "height":25},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店/u27.png"}}]}},
  "masters":{
    "c0a6f8e65f9843a4bd1f1d0f4546bc5c":{
      "packageId":"c0a6f8e65f9843a4bd1f1d0f4546bc5c",
      "type":"Axure:Master",
      "name":"产品管理",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"5024326008c74a3f90f4004ca3eb09ad",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":1364,
                "height":667}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3533708ddaf64d53ab22ac58fbcf7457",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1364,
                    "height":667}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/酒店/u1.png"}},
{
            "id":"b3d7ad7f6d44402fbfdfac4c0f1e8cb0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":140,
                "y":76},
              "size":{
                "width":1226,
                "height":591},
              "linePattern":"none"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b3e89a31a0f041cbbc6ef6f867f6e9ca",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":140,
                    "y":76},
                  "size":{
                    "width":1226,
                    "height":591},
                  "linePattern":"none"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/酒店/u3.png"}}]}}},
  "objectPaths":{
    "5d6a717480f248bda00cb2c40f8af297":{
      "scriptId":"u0",
      "5024326008c74a3f90f4004ca3eb09ad":{
        "scriptId":"u1"},
      "3533708ddaf64d53ab22ac58fbcf7457":{
        "scriptId":"u2"},
      "b3d7ad7f6d44402fbfdfac4c0f1e8cb0":{
        "scriptId":"u3"},
      "b3e89a31a0f041cbbc6ef6f867f6e9ca":{
        "scriptId":"u4"}},
    "ebed7bace75144b6b8b59bcbef2c43e1":{
      "scriptId":"u5"},
    "a805771be51c4627bd31ca58be508dad":{
      "scriptId":"u6"},
    "22727e756455415e8e5506e4724d909b":{
      "scriptId":"u7"},
    "5ad84368cd774defb45a32850c3330f3":{
      "scriptId":"u8"},
    "7842f877a34b4c8aa28bc7207d230b3a":{
      "scriptId":"u9"},
    "1475e2f991d84713a7ec0ca810b98fa2":{
      "scriptId":"u10"},
    "1d55a7c2b33a434698234b69cce5e18e":{
      "scriptId":"u11"},
    "71fc513c19ce4ddf8f921d0c0774a2d7":{
      "scriptId":"u12"},
    "88e25e05b941422f8df900f90d952996":{
      "scriptId":"u13"},
    "8dd9ea69f77d4e6c890757d0f29e3961":{
      "scriptId":"u14"},
    "b19c75706c294640a275eef0000e1fc2":{
      "scriptId":"u15"},
    "ea99017dd72f41bc9e0ecf0bb58a552a":{
      "scriptId":"u16"},
    "88f07d510ce448e19b0d0d2de85c39f5":{
      "scriptId":"u17"},
    "5daa9d8657644f9191d5ae93c7a8462b":{
      "scriptId":"u18"},
    "ee3e1bb89550445f85878d851f41a9e5":{
      "scriptId":"u19"},
    "6ffd489d6e2d458da0e2bee4fc3348ff":{
      "scriptId":"u20"},
    "feda9d9e9f6e4953ba4b918a0c9c78e0":{
      "scriptId":"u21"},
    "7dff947e1168420aa6308b0aef6c983e":{
      "scriptId":"u22"},
    "947a219d4e6e4d0db5ec756027d7f3f0":{
      "scriptId":"u23"},
    "f574132c43f549d0ba1902e759c46172":{
      "scriptId":"u24"},
    "969ba3b74f294597ad962dbe6498fa28":{
      "scriptId":"u25"},
    "97200eef22bd454db4290ee9905f6c9d":{
      "scriptId":"u26"},
    "eaadd7b7a9944638a5abb2a70874645e":{
      "scriptId":"u27"},
    "91f36bf6ac2d4cec82681a2055a3a7ac":{
      "scriptId":"u28"},
    "ee9bb7b7e7ed48809644353c09134dac":{
      "scriptId":"u29"},
    "5194637f1d474c2e9e1261009f790b66":{
      "scriptId":"u30"},
    "8bc4af3849fb42bcaca13c47b596d6b7":{
      "scriptId":"u31"},
    "cb35206aac2c4066b0837cb42e8bd064":{
      "scriptId":"u32"},
    "139ba8e2d0ca400e87abb1bbbccfd4a1":{
      "scriptId":"u33"},
    "e3dc10eeeb28420eb0346fe4f7e859e8":{
      "scriptId":"u34"},
    "ef71128646e349d0a7f6a69c6f5c63f7":{
      "scriptId":"u35"},
    "b1522abb00d54d91a72991bcc2516d1a":{
      "scriptId":"u36"},
    "c3ebf4ddbe234b8f9a0d077dbb71033e":{
      "scriptId":"u37"}}});